### ISSUE TITLE
Effort controller implementation 

### ISSUE THREAD

**Issue by nag92** [UniversalRobots/Universal_Robots_ROS_Driver#105]
I am trying to use the UR10 with a force-torque sensors to develop a haptic system. Does this drive have effort control? I am trying to build an impedance controller for the UR10.

**Comment by fmauch** [comment]
As the underlying hardware doesn't offer an effort control interface, this driver does neither.

**Comment by gavanderhoorn** [comment]
As an alternative, the recently merged velocity control interface could perhaps be used (#1). Not as nice, but better than nothing.
