### ISSUE TITLE
Fail to build the package in catkin workspace

### ISSUE THREAD

**Issue by XYHong18** [UniversalRobots/Universal_Robots_ROS_Driver#11]
Hi,
I followed your instruction to git clone this repository and universal_robot, and install all the dependencies. But I failed to build the package using command "catkin_make". 

I am using Ubuntu 16.04, ROS kinetic, UR5e of version 5.1.0.

Below is my error:

Base path: /home/xinyi/catkin_ws
Source space: /home/xinyi/catkin_ws/src
Build space: /home/xinyi/catkin_ws/build
Devel space: /home/xinyi/catkin_ws/devel
Install space: /home/xinyi/catkin_ws/install
####
####
####
####
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target _ur_msgs_generate_messages_check_deps_SetPayload
[  0%] Built target _ur_msgs_generate_messages_check_deps_ToolDataMsg
[  0%] Built target _ur_msgs_generate_messages_check_deps_Digital
[  0%] Built target _ur_msgs_generate_messages_check_deps_IOStates
[  0%] Built target _ur_msgs_generate_messages_check_deps_SetSpeedSliderFraction
[  0%] Built target _ur_msgs_generate_messages_check_deps_SetIO
[  0%] Built target _ur_msgs_generate_messages_check_deps_MasterboardDataMsg
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target _ur_msgs_generate_messages_check_deps_RobotStateRTMsg
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target controller_manager_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target controller_manager_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target controller_manager_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target controller_manager_msgs_generate_messages_eus
[  0%] Built target controller_manager_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target ur_driver_gencfg
[  0%] Built target _ur_msgs_generate_messages_check_deps_RobotModeDataMsg
[  0%] Built target _catkin_empty_exported_target
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target _ur_msgs_generate_messages_check_deps_Analog
[  2%] Built target ur_hardware_interface
[  2%] Built target sensor_msgs_generate_messages_eus
[  5%] Built target kinect2_registration
[  5%] Built target sensor_msgs_generate_messages_py
[  5%] Built target sensor_msgs_generate_messages_lisp
[  5%] Built target sensor_msgs_generate_messages_cpp
[  5%] Built target geometry_msgs_generate_messages_cpp
[  5%] Built target geometry_msgs_generate_messages_py
[  5%] Built target geometry_msgs_generate_messages_eus
[  5%] Built target geometry_msgs_generate_messages_nodejs
[  5%] Built target tf2_msgs_generate_messages_eus
[  5%] Built target geometry_msgs_generate_messages_lisp
[  5%] Built target tf2_msgs_generate_messages_py
[  5%] Built target tf2_msgs_generate_messages_lisp
[  5%] Built target actionlib_msgs_generate_messages_nodejs
[  5%] Built target actionlib_msgs_generate_messages_py
[  5%] Built target tf_generate_messages_lisp
[  5%] Built target tf_generate_messages_nodejs
[  5%] Built target actionlib_generate_messages_cpp
[  5%] Built target tf_generate_messages_cpp
[  5%] Built target actionlib_generate_messages_eus
[  5%] Built target actionlib_msgs_generate_messages_eus
[  5%] Built target actionlib_generate_messages_lisp
[  5%] Built target actionlib_msgs_generate_messages_lisp
[  5%] Built target tf2_msgs_generate_messages_cpp
[  5%] Built target tf_generate_messages_py
[  5%] Built target actionlib_generate_messages_nodejs
[  5%] Built target actionlib_msgs_generate_messages_cpp
[  5%] Built target tf_generate_messages_eus
[  5%] Built target trajectory_msgs_generate_messages_nodejs
[  5%] Built target tf2_msgs_generate_messages_nodejs
[  5%] Built target actionlib_generate_messages_py
[  5%] Built target trajectory_msgs_generate_messages_lisp
[  5%] Built target std_srvs_generate_messages_cpp
[  5%] Built target trajectory_msgs_generate_messages_cpp
[  5%] Built target industrial_msgs_generate_messages_py
[  5%] Built target control_msgs_generate_messages_py
[  5%] Built target industrial_msgs_generate_messages_nodejs
[  5%] Built target trajectory_msgs_generate_messages_eus
[  5%] Built target industrial_msgs_generate_messages_lisp
[  5%] Built target control_msgs_generate_messages_eus
[  5%] Built target std_srvs_generate_messages_nodejs
[  5%] Built target control_msgs_generate_messages_cpp
[  5%] Built target control_msgs_generate_messages_nodejs
[  5%] Built target trajectory_msgs_generate_messages_py
[  5%] Built target industrial_msgs_generate_messages_cpp
[  5%] Built target std_srvs_generate_messages_eus
[  5%] Built target industrial_msgs_generate_messages_eus
[  5%] Built target control_msgs_generate_messages_lisp
[  5%] Built target std_srvs_generate_messages_lisp
[  5%] Built target std_srvs_generate_messages_py
[  7%] Built target ur10_kin
[  8%] Built target ur3_kin
[ 10%] Built target ur5_kin
[ 10%] Built target control_toolbox_generate_messages_nodejs
[ 10%] Built target dynamic_reconfigure_generate_messages_py
[ 10%] Built target dynamic_reconfigure_gencfg
[ 10%] Built target dynamic_reconfigure_generate_messages_cpp
[ 10%] Built target dynamic_reconfigure_generate_messages_lisp
[ 10%] Built target dynamic_reconfigure_generate_messages_eus
[ 10%] Built target dynamic_reconfigure_generate_messages_nodejs
[ 10%] Built target control_toolbox_generate_messages_lisp
[ 10%] Built target control_toolbox_generate_messages_cpp
[ 10%] Built target control_toolbox_generate_messages_eus
[ 10%] Built target control_toolbox_generate_messages_py
[ 10%] Built target control_toolbox_gencfg
[ 17%] Built target ur_msgs_generate_messages_cpp
[ 25%] Built target ur_msgs_generate_messages_nodejs
[ 25%] Generating Python from MSG ur_msgs/Analog
[ 33%] Built target ur_msgs_generate_messages_eus
[ 35%] Generating Python from MSG ur_msgs/ToolDataMsg
[ 42%] Built target ur_msgs_generate_messages_lisp
[ 43%] Generating Python from MSG ur_msgs/MasterboardDataMsg
[ 46%] Built target kinect2_bridge_nodelet
[ 48%] Built target controller_stopper_node
[ 50%] Built target kinect2_bridge
[ 50%] Generating Python from MSG ur_msgs/Digital
[ 51%] Generating Python from MSG ur_msgs/IOStates
[ 52%] Built target kinect2_calibration
[ 52%] Generating Python from MSG ur_msgs/RobotStateRTMsg
[ 55%] Built target ur10_moveit_plugin
[ 55%] Built target kinect2_viewer
[ 56%] Generating Python from MSG ur_msgs/RobotModeDataMsg
[ 58%] Built target ur5_moveit_plugin
[ 60%] Generating Python code from SRV ur_msgs/SetSpeedSliderFraction
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:72: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_Analog.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_Analog.py] Error 1
make[2]: *** Waiting for unfinished jobs....
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:77: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_ToolDataMsg.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_ToolDataMsg.py] Error 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:82: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_MasterboardDataMsg.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_MasterboardDataMsg.py] Error 1
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:87: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_Digital.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_Digital.py] Error 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:94: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_IOStates.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_IOStates.py] Error 1
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
[ 61%] Built target ur_controllers
[ 62%] Built target ur3_moveit_plugin
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:99: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_RobotStateRTMsg.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_RobotStateRTMsg.py] Error 1
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:104: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_RobotModeDataMsg.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/msg/_RobotModeDataMsg.py] Error 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/gensrv_py.py", line 43, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/build.make:109: recipe for target '/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/srv/_SetSpeedSliderFraction.py' failed
make[2]: *** [/home/xinyi/catkin_ws/devel/lib/python3/dist-packages/ur_msgs/srv/_SetSpeedSliderFraction.py] Error 1
CMakeFiles/Makefile2:1047: recipe for target 'universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/all' failed
make[1]: *** [universal_robot/ur_msgs/CMakeFiles/ur_msgs_generate_messages_py.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

I doubt if the issue is caused by python version.
And below is what I get if I use command "echo $PYTHONPATH":

/opt/ros/kinetic/lib/python2.7/dist-packages:/home/xinyi/catkin_ws/devel/lib/python3/dist-packages:/usr/lib/python2.7/dist-packages

Thanks for your help!
Best.

**Comment by fmauch** [comment]
There seems to be some misconfiguration in your python setup, as you are using python 2.7 (which is normal) and python3 inside your workspace (Which doesn't play along well)

Try cleaning your workspace (deleting build, devel and install), open a new shell and make sure nothing python3 related is getting sourced. Then, try to rebuild.

**Comment by gavanderhoorn** [comment]
I can confirm this.

@XYHong18: see one of the many Q&As on ROS Answers about this: [site:answers.ros.org no module named error](https://www.google.nl/search?q=no+module+named+error++site%3Aanswers.ros.org).

**Comment by XYHong18** [comment]
@fmauch @gavanderhoorn Thanks for your reply! Problem solved!

**Comment by Karthik-Ranga** [comment]
I know this is a closed issue, but is it possible to run the driver under python 3? I need to do this so I can integrate UR with another system. I get a failed catkin_make. is there a workaround? I know it is the problem with ROS.
I built the whole ROS melodic under python 3 and I get the error "ModuleNotFoundError" during catkin_make.

**Comment by gavanderhoorn** [comment]
There is almost zero use of Python in these packages (only a single script IIRC).

A build error from `catkin_make` also does not seem like something we can do anything about here.

I'd recommend posting this to a more suitable forum.
