### ISSUE TITLE
Optimizing gains (PID values) 

### ISSUE THREAD

**Issue by satvu** [UniversalRobots/Universal_Robots_ROS_Driver#119]
# Summary
Is there a way to optimize gains (PID values) for ur5e on the controller using the driver? I'm new to ROS and UR, so sorry if this is common knowledge. I'd like get the right settings so that I can use the velocity controller optimally. 

# Versions
- ROS Driver version: Kinetic
- Affected Robot Software Version(s): 5.3.0
- Affected Robot Hardware Version(s):
- Robot Serial Number: ur5e
- UR+ product(s) installed:
- URCaps Software version(s): externalcontrol-1.0.1.urcap

# Impact
Having difficulty using the velocity controller and trying to resolve that by optimizing the gains. I played around with one of the joints' respective values and it the velocity controller seemed to work better for that joint.

**Comment by fmauch** [comment]
Controller gains are setup in [controller config file](../blob/master/ur_robot_driver/config/ur5e_controllers.yaml) 

Any contribution with optimized values is more than welcome.

**Comment by gavanderhoorn** [comment]
And a note: most/some `ros_control` controllers support [dynamic_reconfigure](http://wiki.ros.org/dynamic_reconfigure), which makes tuning things like PID values a lot more efficient.

**Comment by gavanderhoorn** [comment]
Did you find something which works for you?

**Comment by satvu** [comment]
> Did you find something which works for you?

Scope of our project no longer needs it, but I can reopen this in case this is an issue that other people are interested in or have solutions to.

**Comment by stefanscherzinger** [comment]
Feel free to re-open if this becomes an issue again or if you would like to share PID gains for other users.
