### ISSUE TITLE
Switch Travis integration to the app?

### ISSUE THREAD

**Issue by gavanderhoorn** [UniversalRobots/Universal_Robots_ROS_Driver#144]
Just noting this here as a TODO: Travis migrated from the old integration to the app.

I believe recent PRs don't get CI run any more as the old integration has been turned off/disabled.

**Comment by fmauch** [comment]
Thanks for notifying!

**Comment by gavanderhoorn** [comment]
Could also have been the recent problems Travis has reported: https://www.traviscistatus.com/ (search for "March 26").

**Comment by fmauch** [comment]
As for #148 the build has succeeded on [travis.org](https://travis-ci.org/github/UniversalRobots/Universal_Robots_ROS_Driver/builds/667627387), but it does not show up on GH.

It might be a good opportunity to migrate towards GH actions to reduce the number of services involved...

**Comment by fmauch** [comment]
Changed travis integration, so it is working again.
