### ISSUE TITLE
Can't start ur_robot_driver on the terminal

### ISSUE THREAD

**Issue by tonkei0361** [UniversalRobots/Universal_Robots_ROS_Driver#147]
# Versions
 - Affected Robot Software Version(s): 5.3.0.64176
 - URCaps Software version(s): 1.0.1

# Issue details
I have a UR5e robot and have followed the instruction on this repository, including the installation of URCaps to include external control feature. The robot is connected to the host computer via Ethernet cable and I set the robot's IP address to the IP address of this Ethernet connection. However, when I do 

`$ roslaunch ur_robot_driver ur5e_bringup.launch robot_ip:=myipaddress`

the driver fails to start with these errors on the terminal:

![Screenshot from 2020-03-26 17-10-09](https://user-images.githubusercontent.com/24822732/77697650-a18e1c00-6f85-11ea-83a0-e37c76c5f124.png)

What I don't understand is that after starting urdriver, the port following the IP address is 30002, not 50002. Could this be the issue? If so, how can I make this correct?

Thank you!

**Comment by gavanderhoorn** [comment]
> The robot is connected to the host computer via Ethernet cable and I set the robot's IP address to the IP address of this Ethernet connection

The robot controller and your PC should each have their own IP address. You cannot give two devices on the same network the same IP address.

**Comment by tonkei0361** [comment]
> The robot controller and your PC should each have their own IP address. You cannot give two devices on the same network the same IP address.

Thank you, I messed up the robot's network IP address and never use the correct IP address for parameter `robot_ip` on ROS terminal. The robot is now connected.
