### ISSUE TITLE
Consider lowering action server state reporting frequency

### ISSUE THREAD

**Issue by gavanderhoorn** [UniversalRobots/Universal_Robots_ROS_Driver#151]
@fmauch wrote in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/138#issuecomment-605828287:
> I think the `state_publish_rate` is the same as the control loop rate only for legacy reasons as this was the same in the `ur_modern_driver` for CBx series and every 125 Hz was replaced by 500Hz and later by `*loop_hz` without putting too much thought into that...

We might want to consider lowering the `state_publish_rate` of the various actionlib based controllers.

As these are typically long(er) running actions with more discrete state changes, publishing their state (ie: those of the actions, not of the robot) at 500 Hz seems wasteful (as the state has probably not changed sufficiently to be of interest).

**Comment by gavanderhoorn** [comment]
I can quickly fix this, but a bit of discussion about a rate would be good.

The default is 25 Hz I believe.

Would 50 Hz be acceptable here?

It would still be something users could change, would they so desire.

**Comment by fmauch** [comment]
According to [the docs](http://wiki.ros.org/joint_trajectory_controller#Parameters) the default value is 50 Hz. I think, it would be fine to stick with that.

**Comment by gavanderhoorn** [comment]
> According to [the docs](http://wiki.ros.org/joint_trajectory_controller#Parameters) the default value is 50 Hz. I think, it would be fine to stick with that.

It is: [ros-controls/ros_controllers/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h](https://github.com/ros-controls/ros_controllers/blob/1fd8d25707e289700743925c93644b4295b1c486/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h#L218).

I'll set it to that value.

**Comment by gavanderhoorn** [comment]
See #221.

**Comment by fmauch** [comment]
Closed via #221
