### ISSUE TITLE
Suggestion: use sub(sub)sections for entries in the ROS API docs

### ISSUE THREAD

**Issue by gavanderhoorn** [UniversalRobots/Universal_Robots_ROS_Driver#155]
It's difficult to link to entries like topics and service documentation as they are formatted as bold, inline text.

As Github doesn't allow references to specific lines in a rendered `.md` doc (only through the *Blame* page, which doesn't render it), it would be nice if sub(sub)sections could be used instead, as links to subsections are automatically created by Github when rendering an `.md`.

**Comment by fmauch** [comment]
Good point. I'll take that over to `catkin_doc` as I'm working on that currently, anyway :-)

**Comment by gavanderhoorn** [comment]
Right.

I should've posted this there.

I'll close this one.
