### ISSUE TITLE
Model of internal controller

### ISSUE THREAD

**Issue by macsmitty** [UniversalRobots/Universal_Robots_ROS_Driver#159]
Hi!
I'm trying to approximate the internal controller model of the Ur10 to use it in Simulation (approximate torques from position deviations). I need to approximate a similar model to achieve similar behaviour especially in contact richt scenarios. Are there any model approximations available that you know of?
I recorded some trajectories and could not yet make total sense of them, but I noticed something:

the target_q does not correspond to the control sequence I send to the controller. There seems to be some kind of smoothening happening. I assume that's the smoothening that is mentioned in the urscript documentation about servoj(). Does anyone know the algorithm that is used in this smoothening function? (see plot below)
image
![image](https://user-images.githubusercontent.com/31314526/78799829-f89ae480-79ba-11ea-9b23-f947d7d62c6b.png)

Furthermore, any help regarding a methodology to identify the behaviour of the internal controller is highly appreciated.

**Comment by fmauch** [comment]
I don't feel I can answer your question completely. My first question would be: Which interface did you use for commanding and for creating the plots?

**Comment by fmauch** [comment]
Any updates on this?
