### ISSUE TITLE
Can the tool communication work on the ur5, not the e series ?

### ISSUE THREAD

**Issue by forbiddenname** [UniversalRobots/Universal_Robots_ROS_Driver#164]
tks

**Comment by gavanderhoorn** [comment]
Only the e-Series has the embedded RS485 port on the flange. So no, the regular (ie: non-e-Series) cannot make use of the tool communication functionality.

**Comment by forbiddenname** [comment]
Thanks for your reply. May I ask if there is any way to control the two-finger  through the panel, but you can subscribe the state of two-finger in ros by the ur5 controller connected to ros. sadsadsad.
