### ISSUE TITLE
Can't accept new commands. Controller is not running.

### ISSUE THREAD

**Issue by TFLQW** [UniversalRobots/Universal_Robots_ROS_Driver#165]
# Summary

Connect the ROS with URSIM using ros_control.
First, I have install the URCaps in the ursim. 
Then, I have execute the command 'roslaunch ur_robot_driver ur5_bringup.launch robot_ip:=127.0.0.1' then I start the program in the ursim by plugin the external control, in the  terminal I have got the message:
` INFO] [1588149911.373263600]: Robot requested program
[ INFO] [1588149911.373427040]: Sent program to robot
[ INFO] [1588149911.476540546]: Robot ready to receive control commands.
`
#Issue
First, in a new terminal I execute 'rostopic echo /joint_states' I could get the joint position in URsim.This part indicated that I have got connect with the robot in URsim.
But the problem is that : When I try to start a now node to publish a message to the 'pos_traj_controller/command' , the error in the terminal show that: 
**[ERROR] [1588150073.314638437]: Can't accept new commands. Controller is not running.**
The rqt_graph is like that:
![rosgraph-1](https://user-images.githubusercontent.com/34564497/80578921-c1f53e80-8a3b-11ea-8e9a-cd3b3cfdcb28.png)

The whole terminal message like that
`PARAMETERS
 * /controller_stopper/consistent_controllers: ['joint_state_con...
 * /force_torque_sensor_controller/publish_rate: 125
 * /force_torque_sensor_controller/type: force_torque_sens...
 * /hardware_control_loop/loop_hz: 125
 * /hardware_interface/joints: ['shoulder_pan_jo...
 * /joint_group_vel_controller/joints: ['shoulder_pan_jo...
 * /joint_group_vel_controller/type: velocity_controll...
 * /joint_state_controller/publish_rate: 125
 * /joint_state_controller/type: joint_state_contr...
 * /pos_traj_controller/action_monitor_rate: 10
 * /pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /pos_traj_controller/constraints/elbow_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/goal_time: 0.6
 * /pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
 * /pos_traj_controller/joints: ['shoulder_pan_jo...
 * /pos_traj_controller/state_publish_rate: 125
 * /pos_traj_controller/stop_trajectory_duration: 0.5
 * /pos_traj_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /robot_status_controller/handle_name: industrial_robot_...
 * /robot_status_controller/publish_rate: 10
 * /robot_status_controller/type: industrial_robot_...
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /scaled_pos_traj_controller/action_monitor_rate: 10
 * /scaled_pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/elbow_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/goal_time: 0.6
 * /scaled_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /scaled_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/joints: ['shoulder_pan_jo...
 * /scaled_pos_traj_controller/state_publish_rate: 125
 * /scaled_pos_traj_controller/stop_trajectory_duration: 0.5
 * /scaled_pos_traj_controller/type: position_controll...
 * /scaled_vel_traj_controller/action_monitor_rate: 10
 * /scaled_vel_traj_controller/constraints/elbow_joint/goal: 0.1
 * /scaled_vel_traj_controller/constraints/elbow_joint/trajectory: 0.1
 * /scaled_vel_traj_controller/constraints/goal_time: 0.6
 * /scaled_vel_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /scaled_vel_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
 * /scaled_vel_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /scaled_vel_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
 * /scaled_vel_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /scaled_vel_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /scaled_vel_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
 * /scaled_vel_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /scaled_vel_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
 * /scaled_vel_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /scaled_vel_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
 * /scaled_vel_traj_controller/gains/elbow_joint/d: 0.1
 * /scaled_vel_traj_controller/gains/elbow_joint/i: 0.05
 * /scaled_vel_traj_controller/gains/elbow_joint/i_clamp: 1
 * /scaled_vel_traj_controller/gains/elbow_joint/p: 5.0
 * /scaled_vel_traj_controller/gains/shoulder_lift_joint/d: 0.1
 * /scaled_vel_traj_controller/gains/shoulder_lift_joint/i: 0.05
 * /scaled_vel_traj_controller/gains/shoulder_lift_joint/i_clamp: 1
 * /scaled_vel_traj_controller/gains/shoulder_lift_joint/p: 5.0
 * /scaled_vel_traj_controller/gains/shoulder_pan_joint/d: 0.1
 * /scaled_vel_traj_controller/gains/shoulder_pan_joint/i: 0.05
 * /scaled_vel_traj_controller/gains/shoulder_pan_joint/i_clamp: 1
 * /scaled_vel_traj_controller/gains/shoulder_pan_joint/p: 5.0
 * /scaled_vel_traj_controller/gains/wrist_1_joint/d: 0.1
 * /scaled_vel_traj_controller/gains/wrist_1_joint/i: 0.05
 * /scaled_vel_traj_controller/gains/wrist_1_joint/i_clamp: 1
 * /scaled_vel_traj_controller/gains/wrist_1_joint/p: 5.0
 * /scaled_vel_traj_controller/gains/wrist_2_joint/d: 0.1
 * /scaled_vel_traj_controller/gains/wrist_2_joint/i: 0.05
 * /scaled_vel_traj_controller/gains/wrist_2_joint/i_clamp: 1
 * /scaled_vel_traj_controller/gains/wrist_2_joint/p: 5.0
 * /scaled_vel_traj_controller/gains/wrist_3_joint/d: 0.1
 * /scaled_vel_traj_controller/gains/wrist_3_joint/i: 0.05
 * /scaled_vel_traj_controller/gains/wrist_3_joint/i_clamp: 1
 * /scaled_vel_traj_controller/gains/wrist_3_joint/p: 5.0
 * /scaled_vel_traj_controller/joints: ['shoulder_pan_jo...
 * /scaled_vel_traj_controller/state_publish_rate: 125
 * /scaled_vel_traj_controller/stop_trajectory_duration: 0.5
 * /scaled_vel_traj_controller/type: velocity_controll...
 * /scaled_vel_traj_controller/velocity_ff/elbow_joint: 1.0
 * /scaled_vel_traj_controller/velocity_ff/shoulder_lift_joint: 1.0
 * /scaled_vel_traj_controller/velocity_ff/shoulder_pan_joint: 1.0
 * /scaled_vel_traj_controller/velocity_ff/wrist_1_joint: 1.0
 * /scaled_vel_traj_controller/velocity_ff/wrist_2_joint: 1.0
 * /scaled_vel_traj_controller/velocity_ff/wrist_3_joint: 1.0
 * /speed_scaling_state_controller/publish_rate: 125
 * /speed_scaling_state_controller/type: ur_controllers/Sp...
 * /ur_hardware_interface/headless_mode: False
 * /ur_hardware_interface/input_recipe_file: /home/tiboy/ur_co...
 * /ur_hardware_interface/kinematics/forearm/pitch: 0
 * /ur_hardware_interface/kinematics/forearm/roll: 0
 * /ur_hardware_interface/kinematics/forearm/x: -0.425
 * /ur_hardware_interface/kinematics/forearm/y: 0
 * /ur_hardware_interface/kinematics/forearm/yaw: 0
 * /ur_hardware_interface/kinematics/forearm/z: 0
 * /ur_hardware_interface/kinematics/hash: calib_20954911754...
 * /ur_hardware_interface/kinematics/shoulder/pitch: 0
 * /ur_hardware_interface/kinematics/shoulder/roll: 0
 * /ur_hardware_interface/kinematics/shoulder/x: 0
 * /ur_hardware_interface/kinematics/shoulder/y: 0
 * /ur_hardware_interface/kinematics/shoulder/yaw: 0
 * /ur_hardware_interface/kinematics/shoulder/z: 0.089159
 * /ur_hardware_interface/kinematics/upper_arm/pitch: 0
 * /ur_hardware_interface/kinematics/upper_arm/roll: 1.570796327
 * /ur_hardware_interface/kinematics/upper_arm/x: 0
 * /ur_hardware_interface/kinematics/upper_arm/y: 0
 * /ur_hardware_interface/kinematics/upper_arm/yaw: 0
 * /ur_hardware_interface/kinematics/upper_arm/z: 0
 * /ur_hardware_interface/kinematics/wrist_1/pitch: 0
 * /ur_hardware_interface/kinematics/wrist_1/roll: 0
 * /ur_hardware_interface/kinematics/wrist_1/x: -0.39225
 * /ur_hardware_interface/kinematics/wrist_1/y: 0
 * /ur_hardware_interface/kinematics/wrist_1/yaw: 0
 * /ur_hardware_interface/kinematics/wrist_1/z: 0.10915
 * /ur_hardware_interface/kinematics/wrist_2/pitch: 0
 * /ur_hardware_interface/kinematics/wrist_2/roll: 1.570796327
 * /ur_hardware_interface/kinematics/wrist_2/x: 0
 * /ur_hardware_interface/kinematics/wrist_2/y: -0.09465
 * /ur_hardware_interface/kinematics/wrist_2/yaw: 0
 * /ur_hardware_interface/kinematics/wrist_2/z: -1.9413039509e-11
 * /ur_hardware_interface/kinematics/wrist_3/pitch: 3.14159265359
 * /ur_hardware_interface/kinematics/wrist_3/roll: 1.57079632659
 * /ur_hardware_interface/kinematics/wrist_3/x: 0
 * /ur_hardware_interface/kinematics/wrist_3/y: 0.0823
 * /ur_hardware_interface/kinematics/wrist_3/yaw: 3.14159265359
 * /ur_hardware_interface/kinematics/wrist_3/z: -1.68800121668e-11
 * /ur_hardware_interface/output_recipe_file: /home/tiboy/ur_co...
 * /ur_hardware_interface/reverse_port: 50001
 * /ur_hardware_interface/robot_ip: 127.0.0.1
 * /ur_hardware_interface/script_file: /home/tiboy/ur_co...
 * /ur_hardware_interface/script_sender_port: 50002
 * /ur_hardware_interface/tf_prefix: 
 * /ur_hardware_interface/tool_baud_rate: 115200
 * /ur_hardware_interface/tool_parity: 0
 * /ur_hardware_interface/tool_rx_idle_chars: 1.5
 * /ur_hardware_interface/tool_stop_bits: 1
 * /ur_hardware_interface/tool_tx_idle_chars: 3.5
 * /ur_hardware_interface/tool_voltage: 0
 * /ur_hardware_interface/use_tool_communication: False
 * /vel_traj_controller/action_monitor_rate: 10
 * /vel_traj_controller/constraints/elbow_joint/goal: 0.1
 * /vel_traj_controller/constraints/elbow_joint/trajectory: 0.1
 * /vel_traj_controller/constraints/goal_time: 0.6
 * /vel_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /vel_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
 * /vel_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /vel_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
 * /vel_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /vel_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /vel_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
 * /vel_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /vel_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
 * /vel_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /vel_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
 * /vel_traj_controller/gains/elbow_joint/d: 0.1
 * /vel_traj_controller/gains/elbow_joint/i: 0.05
 * /vel_traj_controller/gains/elbow_joint/i_clamp: 1
 * /vel_traj_controller/gains/elbow_joint/p: 5.0
 * /vel_traj_controller/gains/shoulder_lift_joint/d: 0.1
 * /vel_traj_controller/gains/shoulder_lift_joint/i: 0.05
 * /vel_traj_controller/gains/shoulder_lift_joint/i_clamp: 1
 * /vel_traj_controller/gains/shoulder_lift_joint/p: 5.0
 * /vel_traj_controller/gains/shoulder_pan_joint/d: 0.1
 * /vel_traj_controller/gains/shoulder_pan_joint/i: 0.05
 * /vel_traj_controller/gains/shoulder_pan_joint/i_clamp: 1
 * /vel_traj_controller/gains/shoulder_pan_joint/p: 5.0
 * /vel_traj_controller/gains/wrist_1_joint/d: 0.1
 * /vel_traj_controller/gains/wrist_1_joint/i: 0.05
 * /vel_traj_controller/gains/wrist_1_joint/i_clamp: 1
 * /vel_traj_controller/gains/wrist_1_joint/p: 5.0
 * /vel_traj_controller/gains/wrist_2_joint/d: 0.1
 * /vel_traj_controller/gains/wrist_2_joint/i: 0.05
 * /vel_traj_controller/gains/wrist_2_joint/i_clamp: 1
 * /vel_traj_controller/gains/wrist_2_joint/p: 5.0
 * /vel_traj_controller/gains/wrist_3_joint/d: 0.1
 * /vel_traj_controller/gains/wrist_3_joint/i: 0.05
 * /vel_traj_controller/gains/wrist_3_joint/i_clamp: 1
 * /vel_traj_controller/gains/wrist_3_joint/p: 5.0
 * /vel_traj_controller/joints: ['shoulder_pan_jo...
 * /vel_traj_controller/state_publish_rate: 125
 * /vel_traj_controller/stop_trajectory_duration: 0.5
 * /vel_traj_controller/type: velocity_controll...
 * /vel_traj_controller/velocity_ff/elbow_joint: 1.0
 * /vel_traj_controller/velocity_ff/shoulder_lift_joint: 1.0
 * /vel_traj_controller/velocity_ff/shoulder_pan_joint: 1.0
 * /vel_traj_controller/velocity_ff/wrist_1_joint: 1.0
 * /vel_traj_controller/velocity_ff/wrist_2_joint: 1.0
 * /vel_traj_controller/velocity_ff/wrist_3_joint: 1.0

NODES
  /
    controller_stopper (controller_stopper/node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    ros_control_controller_spawner (controller_manager/spawner)
    ros_control_stopped_spawner (controller_manager/spawner)
    ur_hardware_interface (ur_robot_driver/ur_robot_driver_node)
  /ur_hardware_interface/
    ur_robot_state_helper (ur_robot_driver/robot_state_helper)

auto-starting new master
process[master]: started with pid [19792]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f3291652-89f5-11ea-b04d-645a045f04b6
process[rosout-1]: started with pid [19805]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [19822]
process[ur_hardware_interface-3]: started with pid [19823]
process[ros_control_controller_spawner-4]: started with pid [19829]
process[ros_control_stopped_spawner-5]: started with pid [19847]
process[controller_stopper-6]: started with pid [19860]
process[ur_hardware_interface/ur_robot_state_helper-7]: started with pid [19866]
[ INFO] [1588150004.778974395]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1588150004.782369915]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[ INFO] [1588150004.794306682]: Initializing dashboard client
[ INFO] [1588150004.796080508]: Connected: Universal Robots Dashboard Server

[ INFO] [1588150004.862265263]: Initializing urdriver
[ INFO] [1588150004.862554735]: Checking if calibration data matches connected robot.
[ WARN] [1588150004.862854740]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1588150005.083713274]: Calibration checked successfully.
[INFO] [1588150005.257964]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1588150005.260286]: Controller Spawner: Waiting for service controller_manager/load_controller
[ WARN] [1588150005.887566402]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1588150005.889124793]: Setting up RTDE communication with frequency 125.000000
[ WARN] [1588150006.919579389]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1588150006.919654675]: Loaded ur_robot_driver hardware_interface
[ INFO] [1588150007.044853103]: waitForService: Service [/controller_manager/switch_controller] is now available.
[ INFO] [1588150007.044902166]: Service available.
[ INFO] [1588150007.044945998]: Waiting for controller list service to come up on /controller_manager/list_controllers
[ INFO] [1588150007.045917611]: Service available.
[INFO] [1588150007.080263]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1588150007.083261]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1588150007.085224]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1588150007.086801]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1588150007.087655]: Loading controller: joint_state_controller
[INFO] [1588150007.088889]: Loading controller: pos_traj_controller
[INFO] [1588150007.099369]: Loading controller: scaled_pos_traj_controller
[ INFO] [1588150007.153501060]: Robot mode is now RUNNING
[ INFO] [1588150007.153599012]: Robot's safety mode is now NORMAL
[INFO] [1588150007.157839]: Loading controller: joint_group_vel_controller
[INFO] [1588150007.215984]: Loading controller: speed_scaling_state_controller
[INFO] [1588150007.233155]: Controller Spawner: Loaded controllers: pos_traj_controller, joint_group_vel_controller
[INFO] [1588150007.241366]: Loading controller: force_torque_sensor_controller
[INFO] [1588150007.258197]: Controller Spawner: Loaded controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[INFO] [1588150007.266858]: Started controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[ INFO] [1588150051.483819132]: Robot requested program
[ INFO] [1588150051.483916623]: Sent program to robot
[ INFO] [1588150051.516312704]: Robot ready to receive control commands.
[ERROR] [1588150073.314638437]: Can't accept new commands. Controller is not running.`

# Versions
 - ROS Driver version: kinetic
 - Affected Robot Software Version(s): ursim-3.12.1.90940
 - Affected Robot Hardware Version(s):
 - Robot Serial Number: No
 - UR+ product(s) installed: No
 - URCaps Software version(s): External Control

**Comment by TFLQW** [comment]
I have found the error, because the pos_traj_controllers is not started, so I have change to scaled_pos_traj_controllers ,it's work.

**Comment by TFLQW** [comment]
Actually, the robot in ursim can move by this solution, but in terminal, the error is still alive,'[ERROR] [1588150073.314638437]: Can't accept new commands. Controller is not running' , the robot in ursim is unstable when tracking a circle trajectory in end-effector space. 
  I guess some error maybe occur in the topic publish rate, but I fail to get the right hz to solve this problem, could anyone give me some advice?
The following is the publish rate of '/scaled_pos_traj_controller/comand':
rostopic hz /scaled_pos_traj_controller/command 
subscribed to [/scaled_pos_traj_controller/command]
average rate: 39.701
	min: 0.009s max: 0.046s std dev: 0.01133s window: 36
average rate: 41.183
	min: 0.009s max: 0.059s std dev: 0.01169s window: 79
average rate: 40.075
	min: 0.006s max: 0.112s std dev: 0.01596s window: 117
average rate: 42.361
	min: 0.004s max: 0.112s std dev: 0.01483s window: 166
average rate: 45.836
	min: 0.002s max: 0.112s std dev: 0.01378s window: 225
average rate: 45.249
	min: 0.002s max: 0.112s std dev: 0.01399s window: 268
average rate: 44.509
	min: 0.002s max: 0.112s std dev: 0.01451s window: 307
average rate: 45.359
	min: 0.002s max: 0.112s std dev: 0.01435s window: 359
average rate: 45.708
	min: 0.002s max: 0.115s std dev: 0.01536s window: 408
average rate: 47.252
	min: 0.002s max: 0.115s std dev: 0.01505s window: 469
average rate: 46.887
	min: 0.002s max: 0.115s std dev: 0.01516s window: 511
average rate: 47.862
	min: 0.002s max: 0.115s std dev: 0.01501s window: 571
average rate: 46.900
	min: 0.002s max: 0.115s std dev: 0.01512s window: 605
^Caverage rate: 47.450
	min: 0.002s max: 0.115s std dev: 0.01507s window: 632

**Comment by gavanderhoorn** [comment]
It would help if you could provide some more information.

The "controller not running" message is expected if you don't start the External Control program on the TP. Have you started it? The [quickstart](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#quick-start) documentation describes how to do this, and the [Installing a URCap on a CB3 robot](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/install_urcap_cb3.md) gives more detailed steps.

**Comment by TFLQW** [comment]
@gavanderhoorn 
Hi~, Thanks for your reply. I have confirmed that  I have started the External Control program on TP, and I have also recieve that 
'[ INFO] [1588150051.483819132]: Robot requested program
[ INFO] [1588150051.483916623]: Sent program to robot
[ INFO] [1588150051.516312704]: Robot ready to receive control commands.'
Maybe I will try to use 'JointGroupPositionController', but I am still suspect the topic publish rate not matching.

**Comment by TFLQW** [comment]
@gavanderhoorn 
Hi~, I have just verified the solution as you suggest to change from `JointTrajectoryController` to `JointGroupPositionController`, the error disapears, but the robot in ursim is more unstable and it's hard to track a circle trajectory. Could help me to find the problem?
The robot is like that:
![Peek 2020-05-01 21-15](https://user-images.githubusercontent.com/34564497/80808617-7df86a00-8bf2-11ea-954e-76fdacbad42f.gif)

**Comment by TFLQW** [comment]
@gavanderhoorn
Hi~  I have a good news that I have solved this problem by using  velocity_controllers/JointGroupVelocityController, maybe velocity control is suitable for this kind of tracking problem.

**Comment by fmauch** [comment]
I agree that velocity control is more suitable for this kind of situation.

To add to an earlier post of @gavanderhoorn: The message "Can't accept new commands. Controller is not running" can have two different sources
 
 1. The actual ROS controller is not in a running state, you are trying to use a loaded, but unstarted controller.
 2. The external control mode is not active on the robot as @gavanderhoorn suggested

Technically both boil down to the first version, as controllers will get temporarily stopped when the external control is not active on the robot.
