### ISSUE TITLE
rtde_input_recipe.txt, rtde_output_recipe.txt and servoj.urscript are not installed.

### ISSUE THREAD

**Issue by FelixBlix** [UniversalRobots/Universal_Robots_ROS_Driver#201]
# Summary

# Versions
 - ROS Driver version: ubuntu16.04+kinetic
 - Affected Robot Software Version(s): 3.8.0.61336
 - Affected Robot Hardware Version(s):  UR10
 - Robot Serial Number: 2018301660
 - URCaps Software version(s): external control 1.0.1

# Issue details
Because the rtde_input_recipe.txt, rtde_output_recipe.txt and servoj.urscript are not installed it is not possible to run the driver from install space.

The error output is:
[FATAL] [1592385744.497322358]: Did not receive confirmation on RTDE output recipe.

## Steps to Reproduce
Error occurs when installing driver.

## Workaround Suggestion
A workaround to this problem is to manually copy the files:  rtde_input_recipe.txt, rtde_output_recipe.txt and servoj.urscript to the install space.

**Comment by gavanderhoorn** [comment]
Yes, the `resources` directory should be installed as well.

If you add `resources` here:

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/289655e24ca640c8aa1a6acbfaf6f5fc593dbe2c/ur_robot_driver/CMakeLists.txt#L152-L153

does that solve your problem?
