### ISSUE TITLE
How to display UR10e  speed, acceleration curve in rqt_plot

### ISSUE THREAD

**Issue by tt2cloud** [UniversalRobots/Universal_Robots_ROS_Driver#211]
# Summary

Dear all, I can control the real Hardware  UR10e  movement under Rviz, But I used "rqt_plot"commder,I can't choose the joint_states/position and joint_states/velocity. As the picture shown.

![image](https://user-images.githubusercontent.com/50128330/85950073-0abe6a80-b98d-11ea-8df5-3b5019ebefff.png)

![image](https://user-images.githubusercontent.com/50128330/85950083-21fd5800-b98d-11ea-98be-0f90f057c0ed.png)

I want to view the velocity and acceleration curves of 6 joints through rqt_plot，Could you help me! 
thanks in advance!

**Comment by fmauch** [comment]
Dear @tt2cloud please accept, that this is not a ROS helper forum. This is an issue tracker for the Universal Robots ROS driver. For questions about ROS, please go to [ROS Answers](https://answers.ros.org/questions/)
