### ISSUE TITLE
Force/Impedance control of UR e-series

### ISSUE THREAD

**Issue by deepakraina99** [UniversalRobots/Universal_Robots_ROS_Driver#219]
Is it possible to do cartesian impedance control using ROS for UR e-series? I am able to do with real robot using teach pendant but I wanted it to do through ROS control?
If not, do I have force feedback in UR series (in ROS topics) which can be used to write my own impedance controller?

Thanks.

**Comment by fmauch** [comment]
Currently, this is not supported, no.

You get the wrench published via the `force_torque_sensor_controller` which is started by default and publishes the wrench on `/wrench` (also see #218).

As there is no Cartesian control in ROS-Control (yet), you'll either have to do the inverse kinematics yourself or use something like https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers to get it working.

As we are currently working on a Cartesian controller, this might get things s bit easier to implement soonish (around the end of this year, I assume).

**Comment by deepakraina99** [comment]
Thanks

**Comment by deepakraina99** [comment]
> Currently, this is not supported, no.
> 
> You get the wrench published via the `force_torque_sensor_controller` which is started by default and publishes the wrench on `/wrench` (also see #218).
> 
> As there is no Cartesian control in ROS-Control (yet), you'll either have to do the inverse kinematics yourself or use something like https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers to get it working.
> 
> As we are currently working on a Cartesian controller, this might get things s bit easier to implement soonish (around the end of this year, I assume).

@fmauch Would you be able to implement cartesian control ?

**Comment by fmauch** [comment]
Colleages of me are working on it right now.

**Comment by deepakraina99** [comment]
@fmauch  Any updates on this ?

**Comment by urrsk** [comment]
@deepakraina99 Currently, It is not possible to program your own impedance control loop as the UR controller only supports position and velocity commands and not torque commands. But I am aware of several successful implementation of admittance control loop using both `servoj` and `speedj`.

**Comment by fmauch** [comment]
BTW, Cartesian control is now included into this driver.

**Comment by ZZWang21** [comment]
So, any update? Or anyone has achieved this? I have received the force signal and can adjust the position of the end-effector. How should I combine them? Thank you.

**Comment by 2000222** [comment]
> 

Hope new update....But could u tell us some hint or tutorials about how to receive the force signal and adjust the position of the end-effector~~ Thank u

**Comment by stefanscherzinger** [comment]
@2000222 @deepakraina99 

In case you do not want to write your own controller, let me point to this [control suite](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers#cartesian-controllers). It works great for end-effector force control (among other use cases) on the UR and URe series. [Here](https://github.com/stefanscherzinger/cartesian_controllers_universal_robots)'s an example package on a UR10e.

**Comment by 2000222** [comment]
> @2000222 @deepakraina99
> 
> In case you do not want to write your own controller, let me point to this [control suite](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers#cartesian-controllers). It works great for end-effector force control (among other use cases) on the UR and URe series. [Here](https://github.com/stefanscherzinger/cartesian_controllers_universal_robots)'s an example package on a UR10e.

Thanks a lot! This control suite is so amazing 🤗🤗 and helpful🍻🍻😻😻

**Comment by AdrianPrados** [comment]
Good afternoon, I would like to know if the issue of using an impedance controller on UR robots for ROS1 has been resolved. We have a robot with two UR3e arms and would like to add an impedance control system. We are not sure how to proceed or if there is any completed implementation already available for use. Our arms run with ROS1, so we are unsure whether we can create a launcher from our external computers to control this impedance controller. Thank you very much for your help.

**Comment by urfeex** [comment]
The link in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/219#issuecomment-1307308962 is probably still one of the most helpful.

**Comment by AdrianPrados** [comment]
Thanks for the quick response, my question is if I need to run that controller suit in my computer and connect with my robot by ROS or I need to run it directly on my robot. Thanks for your help.

**Comment by urfeex** [comment]
It is a ROS package, so it will have to run within the ROS driver. See the linked ur10e example.

**Comment by tlpss** [comment]
@urfeex any chance the official drivers will support the new torque interface?

https://www.universal-robots.com/news-and-media/news-center/universal-robots-offers-new-low-level-torque-interface-to-empower-research-and-innovation/

**Comment by urfeex** [comment]
For ROS 2 we do.

**Comment by Nabil-Miri** [comment]
BTW this repo offers Cartesian Impedance Controller using ROS2 for UR with the new Direct Torque Control interface: 
https://github.com/lvjonok/pixi_ur_ros2
