### ISSUE TITLE
Capture robot status

### ISSUE THREAD

**Issue by ipa-hsd** [UniversalRobots/Universal_Robots_ROS_Driver#22]
In case of robot collision, the teach pendant shows a "protective stop" error, but is nowhere captured in ROS. There is a section which is commented out:

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/16cc69ddc1bf5cb944f5e627aeffdaa4fa59ed7c/ur_robot_driver/include/ur_robot_driver/primary/primary_parser.h#L154-L157

The variables are defined but never used:

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/16cc69ddc1bf5cb944f5e627aeffdaa4fa59ed7c/ur_robot_driver/include/ur_robot_driver/primary/robot_state/robot_mode_data.h#L44-L50

Might be interesting to create a PR.

**Comment by fmauch** [comment]
This is currently being developed inside #20
