### ISSUE TITLE
Classic Robot Program besides ROS control

### ISSUE THREAD

**Issue by tragolf** [UniversalRobots/Universal_Robots_ROS_Driver#242]
# Summary

Just a short question. Is it possible to run a classical UR-Program on the robot controller and use the ROS driver just for sending non-interruptive Script commands like set_io, write_register etc. during runtime?

Or is it currently only possible to use ROS OR UR-Prog?

Thanks

Edit: Found this in the description "This will in the future also enable the usage of ROS-components as part of a more complex UR-program on the teach pendant."
This means it is currently not possible or are non-interuptive script commands still possible?

**Comment by fmauch** [comment]
The control part will only be active, when an according program with the ProgramNode from the ExternalControl URCaps will be running on the controller as explained [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#prepare-the-robot).

If this step is skipped, everything apart controlling robot motions will work. See the [`ur_robot_driver` README](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/README.md)

With this you can have a completely different program running on the teach pendant while using the secondary interface or the `set_io` service (which uses RTDE). However, when using an e-Series robot, make sure to put it into remote_control mode if you want to send commands from a remote location (this includes non-disruptive write commands as far as I know).
