### ISSUE TITLE
Latest version (1.3.1) of ur_msgs breaks build

### ISSUE THREAD

**Issue by Doomerdinger** [UniversalRobots/Universal_Robots_ROS_Driver#255]
# Summary

With the latest version of ur_msgs the "payload" field was changed to "mass" (see [#5](https://github.com/ros-industrial/ur_msgs/issues/5)). This breaks the driver.

# Versions
All (melodic?)

# Impact
Build now fails.

Should be simple enough to change "payload" to "mass"

**Comment by Doomerdinger** [comment]
Duplicate.

**Comment by gavanderhoorn** [comment]
Duplicate of #235.
