### ISSUE TITLE
Overshooting joint trajectory controller

### ISSUE THREAD

**Issue by felixvd** [UniversalRobots/Universal_Robots_ROS_Driver#275]
# Summary

Our UR 5e overshoots significantly when executing this trajectory (in reality the robot is upright; the video is rotated):

![ur5e_proplem_motion](https://user-images.githubusercontent.com/4535737/95206340-8d26b800-0821-11eb-8864-5ac0ed91c215.gif)

Sadly, I forgot to take a video of the trajectory in Rviz, but the joint states in the trajectory don't swing back like that. They move monotonously towards the final state (which the robot does arrive at, as well). I uploaded the trajectory in [this yaml file](https://gist.github.com/felixvd/1131e2fee68552622df29376bd71468f)

I would like to know if this behavior is expected and if there is a workaround. It looks as if a velocity controller was struggling to recreate the trajectory, so maybe this is not a bug, but something we need to adjust the settings for? Thanks in advance for any insights.

# Versions
 - ROS Driver version: commit 3ce362
 - Affected Robot Software Version(s): 5.7
 - Affected Robot Hardware Version(s): UR 5e
 - Robot Serial Number: -
 - UR+ product(s) installed: - 
 - URCaps Software version(s): 1.0.2

# Impact
The robot does not stop where it is supposed to.

## Use Case and Setup
We need the robot to follow the trajectory without overshooting this much, as it would break our tools. But we do need the robot to move at least this quickly.

Our robot control loop is running at 500 Hz (according to the config file). In our bringup file, the `scaled_pos_joint_traj_controller` and three others are in the `controllers` argument, and `pos_joint_traj_controller` and `joint_group_vel_controller` are in `stopped_controllers`.

## Steps to Reproduce

You can move the robot to the start state of [this trajectory](https://gist.github.com/felixvd/1131e2fee68552622df29376bd71468f)*, and then execute it by sending it to `/ur_hardware_interface/follow_joint_trajectory/command`

*The start of the trajectory is `[2.981921261631558, -1.27472656822998, 1.3204057526082944, -1.6164710215873699, 3.075542515700016, -6.91763185490812e-07]`.

## Expected Behavior
The robot should follow the trajectory without overshooting.

## Actual Behavior
The overshoot is significant.

## Workaround Suggestion
I can try executing the same trajectory more slowly, but that won't help us (the speed is necessary for our application). Converting the trajectory to a URscript and sending it to the robot controller box could work. If you have any code to share that would be great.

**Comment by felixvd** [comment]
I found [this `do_extrapolate` line](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/resources/ros_control.urscript#L51) in the urscript running on the robot that seems to continue applying joint commands until it receives a new one (is this safe?). To make sure that's not the culprit, I set the value in that line of `ros_control.urscript` to `False`, activated headless mode, and removed the URCap from my robot to be sure that it is the script that is being executed on the robot. Sadly, the problem persists.

I also confirmed that slowing down the trajectory fixes the overshooting (unsurprisingly), but since we need to move and stop quickly, I hope to find a better solution.

**Comment by fmauch** [comment]
My first question would be whether the robot is actually able to execute the fast motion or whether speed scaling is a factor in that execution.You could have a look at the topics `speed_scaling_factor` and `pos_joint_traj_controller/state` to find out more. I've seen such overshoots by the `joint_trajectory_controller` before, when non-realistic constraints are set for the setpoints (e.g. accelerating by a large portion for a very short way. This should show in the `pos_joint_traj_controller/state/desired` field if this is the case. A plot of a relevant axis would be interesting to investigate this further.

**Comment by felixvd** [comment]
We don't touch speed scaling and the pendants are set to full speed.

This is the plot of [this trajectory](https://gist.github.com/felixvd/1131e2fee68552622df29376bd71468f#file-ur5e_problem_trajectory_2-yaml) (technically not the same as in the video, but essentially):

![Screenshot from 2020-10-08 21-02-06](https://user-images.githubusercontent.com/4535737/95456359-2e407a80-09aa-11eb-8d1d-2520588facc9.png) 

It's true and visible in the video that the elbow joint puts in a lot of effort, but it doesn't seem extreme in the plot. I guess there is no official value for the maximum acceleration values. Maybe we will just have to slow down the relevant parts experimentally.

**Comment by gavanderhoorn** [comment]
> We don't touch speed scaling and the pendants are set to full speed.

The question is not whether *you* change the scaling, but whether the safety system in the robot controller does.

**Comment by felixvd** [comment]
I just used `yaml.dump` on the msg object. Is there a better way? The `rospy` documentation is hard to get toright now because the `ros.org` domain seems to have a problem.

I don't know if the robot could handle the trajectory in URScript - I haven't tesated it. Is there an example for how to convert the trajectory to a URScript? I couldn't find one or think of a simple solution.

**Comment by fmauch** [comment]
> I just used yaml.dump on the msg object. Is there a better way? The rospy documentation is hard to get to right now because the ros.org domain seems to have a problem.

I usually use a `rostopic echo -n 1 <topic_name> > output.yaml` to record messages. Also, you recorded the `command` topic, but the `state` topic would be the interesting one, as we can see the desired and actual state there.

> I don't know if the robot could handle the trajectory in URScript - I haven't tested it. Is there an example for how to convert the trajectory to a URScript? I couldn't find one or think of a simple solution.

I'm not sure what a proper conversion would look like as it is hard to translate the spline-interpolated trajectory into waypoint+blending radius notation that is being used for the URScript trajectory.

> There is a little dip. I guess that means the trajectory wasn't considered safe?

At least that means that the "scaling" part of the controller is being used. The robot controller slowed down the commanded motion due to the safety constraints configured on the robot controller.

**Comment by felixvd** [comment]
I see. I didn't know the state topic included that information.

We ended up modifying the motion to avoid the elbow acceleration, although we would have preferred a generally applicable solution to generate safely executable trajectories. Sadly, neither the time parametrization methods we had available out of the box in MoveIt nor slowing down only the sections with high accelerations worked well for us at all.

> I'm not sure what a proper conversion would look like as it is hard to translate the spline-interpolated trajectory into waypoint+blending radius notation that is being used for the URScript trajectory.

Me neither, but I'd be very interested in even an imperfect conversion :)

**Comment by DavidYaonanZhu** [comment]
So the solution is to slow down the trajectory?
