### ISSUE TITLE
whether the "effort" in "/joint_states" topic stand for the joint torques of UR?

### ISSUE THREAD

**Issue by TianXu1991** [UniversalRobots/Universal_Robots_ROS_Driver#286]
# Summary
*Introduction to the issue*
Hi, fmauch. 
In order to idetify the dynamic parameters of UR, I need to read the joint positions, joint velocities and joint torques of UR. I guess the "position" and "velocity" in the "sensor_msgs/JointState" stand for "joint positions" and "joint velocities" in the "/joint_states" topic, respectively. However, I'm not sure whether the meaning of "effort" stand for joint torques of UR.
![Screenshot from 2020-11-10 10-07-42](https://user-images.githubusercontent.com/35133540/98619448-37708e80-233e-11eb-9577-c77c5c877a25.png)
# Versions
 - ROS Driver version: Melodic
 - UR: UR10
 - URCaps Software version(s): 1.0.4

# Impact
*What is the impact of the issue. Try to describe it well enough, in order for us to prioritise the issues.*
Dynamic parameters of robot is necessary for designing the model-based observer, such as collision detection observer. In order to identify these parameters of UR, joint positions, joint velocities and joint torques of UR are needed to read. 

# Issue details
*This part is important in order to clarify the severity of the issue.*
I want to read the joint torques of UR, but  I'm not sure whether the meaning of "effort" in "/joint_states" topic stand for joint torques of UR?
If the "effort" is not the joint torques, how can I get the joint torque readings from this driver? Maybe this issue can be related to #35. 

## Expected Behavior
*What did you expect and why?*
I expect to read the joint positions, joint velocities and joint torques of UR for dynamic parameter identification.

**Comment by fmauch** [comment]
Please see the discussion in #146
