### ISSUE TITLE
ROS / ROS 2 Compatibility

### ISSUE THREAD

**Issue by vanthome** [UniversalRobots/Universal_Robots_ROS_Driver#291]
Sorry in case I have missed it, but I cannot find witch which ROS Versions this module is compatible with. Can you please clarify?
BG

**Comment by gavanderhoorn** [comment]
From [the readme](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/README.md#requirements):

> ### Requirements
> 
> This driver requires a system setup with ROS. It is recommended to use **Ubuntu 18.04 with ROS melodic**, however using Ubuntu 16.04 with ROS kinetic should also work.

**Comment by gavanderhoorn** [comment]
Work for ROS 2 is underway, but not in a usable state right now.

**Comment by gavanderhoorn** [comment]
And ee #69, which was even pinned.

**Comment by vanthome** [comment]
OMG, sorry, I did not look at the pinned ones!

**Comment by gavanderhoorn** [comment]
If your question has been answered, I'd suggest you close your issue.
