### ISSUE TITLE
I can't cmake ur_client.help please.fatal error : variant: There is no such file or directory

### ISSUE THREAD

**Issue by aoligeihahah** [UniversalRobots/Universal_Robots_ROS_Driver#292]
![2020-11-22 22-00-43屏幕截图](https://user-images.githubusercontent.com/72695459/99906064-c9e63a00-2d0f-11eb-9571-07cdc6819abc.png)

**Comment by fmauch** [comment]
Please do not double post. You posted the issue [at the right place](https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/28) already.
