### ISSUE TITLE
Is there any method to set ft-sensor-wrench topic?

### ISSUE THREAD

**Issue by Csp0920** [UniversalRobots/Universal_Robots_ROS_Driver#293]
I find that the ft sensor data is published to /wrench, and I want to change it, such as publishing ft sensor data to my_ft_sensor/wrench.

If I should modify the config in ur_robot_driver/config/ur3e_controllers.yaml?
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController  ------------------(modify this?)
   publish_rate: *loop_hz

**Comment by gavanderhoorn** [comment]
You don't ever (well, perhaps maybe in some special case) have to change code to get ROS nodes to publish on some other topic.

Doing that is a very strong anti-pattern in ROS.

Use [remapping](http://wiki.ros.org/Remapping%20Arguments). See also [#q303611](https://answers.ros.org/question/303611) on ROS Answers.

**Comment by Csp0920** [comment]
> You don't ever (well, perhaps maybe in some special case) have to change code to get ROS nodes to publish on some other topic.
> 
> Doing that is a very strong anti-pattern in ROS.
> 
> Similarly, don't ever add configuration options (ie: parameters) to nodes to set names of topics.
> 
> So the `ForceTorqueSensorController` does not support doing what you ask.
> 
> Use [remapping](http://wiki.ros.org/Remapping%20Arguments). See also [#q303611](https://answers.ros.org/question/303611) on ROS Answers.
> 
> Edit: or alternatively, use namespacing.

Can remap be added to any node? Or can remap only in the node where this topic is published？

**Comment by Csp0920** [comment]
Original launch:
<node name="ros_control_controller_spawner" pkg="controller_manager" type="spawner" respawn="false"
    output="screen" args="$(arg controllers)" />

Modified launch:
<node name="ros_control_controller_spawner" pkg="controller_manager" type="spawner" respawn="false"
    output="screen" args="$(arg controllers)" >
    <remap from="/wrench" to="/my_ft_sensor/wrench" />
</node>

Is that what you said？

**Comment by gavanderhoorn** [comment]
You need to remap the topic for the node which is actually publishing to it.

The `controller_manager` does not publish to `wrench`. That would be the driver itself.

**Comment by Csp0920** [comment]
> 您需要重新映射实际发布到该节点的主题。
> 
> 在`controller_manager`不发布到`wrench`。那将是驱动程序本身。

 <arg name="controllers" default="joint_state_controller scaled_pos_joint_traj_controller speed_scaling_state_controller force_torque_sensor_controller robot_status_controller" doc="Controllers that are activated by default."/>

I find that controller_manager spawns force_torque_sensor_controller. So I think the topic is published here.
Is it right?

**Comment by gavanderhoorn** [comment]
No.

"spawning" just means instructing the `ControllerManager` class *inside* the driver to load a `.so` and instantiating an object from that `.so`.

The code "runs inside" the driver node.

**Comment by Csp0920** [comment]
> No.
> 
> "spawning" just means instructing the `ControllerManager` class _inside_ the driver to load a `.so` and instantiating an object from that `.so`.
> 
> The code "runs inside" the driver node.

But I didn't really see where /wrench was published...

**Comment by Csp0920** [comment]
Is it in here?
<node name="ur_hardware_interface" pkg="ur_robot_driver" type="ur_robot_driver_node" output="screen" launch-prefix="$(arg launch_prefix)" required="true">

**Comment by gavanderhoorn** [comment]
Yes, that's the node which hosts the `ControllerManager` and loads the F/T controller plugin.

**Comment by Csp0920** [comment]
> 是的，那是托管`ControllerManager`并加载F / T控制器插件的节点。

Thank you very much for your patient.

**Comment by Csp0920** [comment]
Hello, after I remap “/wrench” to "/new_wrench".
I got the error: "pipeline producer overflowed! <RTDE Data Pipeline>"
And I felt that my terminal became very laggy.
I see the question＃6. He solved the problem by replacing the PC.
If  this problem related to PC？

**Comment by gavanderhoorn** [comment]
I have not encountered this, so I would not know what the cause would be.

Perhaps @fmauch knows something.

Remapping by itself should not cause this, as it's a one-time thing.

**Comment by fmauch** [comment]
No, I don't. But I'll look into it.

**Comment by fmauch** [comment]
> Hello, after I remap “/wrench” to "/new_wrench".
> When I tried to `rostopic echo /new_wrench`
> I got the error: `pipeline producer overflowed! <RTDE Data Pipeline>`
> And I felt that my terminal became very laggy.
> I see the question＃6. He solved the problem by replacing the PC.
> If this problem related to PC？

Just a couple of questions:
 - Does the `rostopic echo` work without the remap? I would suggest, it behaves the same, as @gavanderhoorn mentioned.
 - Does this happen every time?
 - Do you use a real-time kernel as [suggested](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#requirements)?
 - What is the system load on your system? (You could post the output of `top -n 1`)

**Comment by Csp0920** [comment]
1. Does the `rostopic echo` work without the remap?
I deleted the remap code and tried it, and it won't report a error `pipeline producer overflowed! <RTDE Data Pipeline>`.
However, it is disconnected from the PC from time to time. `Connection to robot dropped, waiting for new connection.`
2. Does this happen every time?
I've tried both cases many times. They happened every time.
3. Do you use a real-time kernel as suggested?
I think I have used rt knernel.
![6fbea3a32920f3bcdb1bcb491f8e7f0](https://user-images.githubusercontent.com/57889345/100689515-923a5a80-33bf-11eb-8a71-42a9b9df8c0d.jpg)
4. What is the system load on your system?
![f9ffcc3d9a17c6164c8bf229ec40a1a](https://user-images.githubusercontent.com/57889345/100689538-9ebeb300-33bf-11eb-8bdb-1ae611a9179f.jpg)

**Comment by Csp0920** [comment]
![微信图片_20201201102500](https://user-images.githubusercontent.com/57889345/100689685-e7766c00-33bf-11eb-9b74-b467b37f084d.jpg)
![微信图片_20201201102813](https://user-images.githubusercontent.com/57889345/100689705-f2c99780-33bf-11eb-8099-c60707db3f72.jpg)

**Comment by Csp0920** [comment]
Hello, after using another better computer, the error will not be happened again.
Thanks for your help.
