### ISSUE TITLE
unused args [kinematics_config] 

### ISSUE THREAD

**Issue by hustfzt2** [UniversalRobots/Universal_Robots_ROS_Driver#303]
when I run: roslaunch ur_robot_driver ur5e_bringup.launch, the following issues are:
unused args [kinematics_config] for include of [/home/fzt/catkin_ws/src/universal_robot/ur_e_description/launch/ur5e_upload.launch]
The traceback for the exception was written to the log file.

**Comment by gavanderhoorn** [comment]
Did you follow the readme, especially the [Building](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/783b1d1f5774220058d0a2aa3dd93185641e8c7e#building) section?

It's important to `clone` the correct repositories.

**Comment by fmauch** [comment]
Closing as a proper solution was proposed. Feel free to reopen or comment if the problem still persists.
