### ISSUE TITLE
externalcontrol-1.0.4.urcap cannot be opened

### ISSUE THREAD

**Issue by ata-shirazi** [UniversalRobots/Universal_Robots_ROS_Driver#314]
When I try to add the URCap file in Setting->URCaps, after opening the file nothing shows up  in URcap Information window. But it can add version 1.0.3 without problem.  

# Versions
 - ROS Driver version:
 - Affected Robot Software Version(s): PolyScope version of 5.9.3.1031212
 - Affected Robot Hardware Version(s): UR5e
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s): externalcontrol-1.0.4.urcap

**Comment by gavanderhoorn** [comment]
What was the solution?
