### ISSUE TITLE
Move until tool contact

### ISSUE THREAD

**Issue by marekcygan** [UniversalRobots/Universal_Robots_ROS_Driver#339]
In the e-series UR robots have the nice teach pendant programming command move until tool contact (even with retraction distance defined). Are there any plans to cover this functionality in the driver?

**Comment by fmauch** [comment]
Currently, this is not planned.

**Comment by marekcygan** [comment]
@fmauch thanks for fast response! Do you recommend some particular way of implementing such a feature on my end? My current plan is to send a piece of UR script with a loop actively checking for `tool_contact` and using `speedl` along the way.

**Comment by ljden** [comment]
@marekcygan did you make any progress with this?

**Comment by marekcygan** [comment]
@ljden sorry for late reply. In the end we used [ur_rtde](https://sdurobotics.gitlab.io/ur_rtde/) and injected a small ur script that actively checks for contact and triggers `stopl`.
