### ISSUE TITLE
Unable to load calibration file from robot

### ISSUE THREAD

**Issue by SCh-J** [UniversalRobots/Universal_Robots_ROS_Driver#341]
# Summary
I'm unable to receive the my_robot_calibration.yaml by launching the ur_calibration calibration_correction.launch file.

# Versions
 - ROS Driver version: 1.14.10
 - Affected Robot Software Version(s): 3.7.2.40245
 - Affected Robot Hardware Version(s): UR10
 - Robot Serial Number: 2015301390
 - UR+ product(s) installed: -
 - URCaps Software version(s): 1.0.4

# Impact
Precise calibration is not possible.

# Issue details
`ur-10@ur10-OptiPlex-9020:~/catkin_ws$ ping -c 4 192.168.0.4
PING 192.168.0.4 (192.168.0.4) 56(84) bytes of data.
64 bytes from 192.168.0.4: icmp_seq=1 ttl=64 time=1.65 ms
64 bytes from 192.168.0.4: icmp_seq=2 ttl=64 time=0.184 ms
64 bytes from 192.168.0.4: icmp_seq=3 ttl=64 time=0.183 ms
64 bytes from 192.168.0.4: icmp_seq=4 ttl=64 time=0.180 ms

--- 192.168.0.4 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3039ms
rtt min/avg/max/mdev = 0.180/0.549/1.651/0.636 ms
ur-10@ur10-OptiPlex-9020:~/catkin_ws$ roslaunch ur_calibration calibration_correction.launch   robot_ip:=<192.168.0.4> target_filename:="${HOME}/my_robot_calibration.yaml"
bash: 192.168.0.4: Datei oder Verzeichnis nicht gefunden
`

## Project status at point of discovered
 - after successfull cmake build

**Comment by gavanderhoorn** [comment]
> ```
> robot_ip:=<192.168.0.4>
> ```

you should not include the `<` nor the `>`.
