### ISSUE TITLE
Multirobot support

### ISSUE THREAD

**Issue by Chemaslane** [UniversalRobots/Universal_Robots_ROS_Driver#347]
Hi,

I'm trying a setup with two different Universal Robots in the same Ros system, and have been able to launch two instances of the driver at the same time, including the "ur_common.launch" file from different namespaces for each robot.

However, some errors arises when launching the second driver, and the rosnode list becomes something like this

![image](https://user-images.githubusercontent.com/65335982/112827790-1a3f2100-908f-11eb-9cc6-93485afa5e93.png)

Is this possible even if I have to make some changes?

**Comment by fmauch** [comment]
This might be a duplicate of #81. Did you check that one?

**Comment by Chemaslane** [comment]
Ups, yes, that's it. Sorry for the duplicate
