### ISSUE TITLE
UR3 teaching pendant stopped

### ISSUE THREAD

**Issue by mywnajsldkf** [UniversalRobots/Universal_Robots_ROS_Driver#351]
# Summary

Hi, I want to connect UR3 hardware with ROS.
But When I start ExternalControl file, teaching pendant screen is stopped. 
How can I solve this problem?

![ur3-teaching-pendant](https://user-images.githubusercontent.com/47661695/115394910-411bed80-a21e-11eb-949a-10a8c47dd62a.jpeg)

# Versions
 - ROS Driver version: Ros melodic
 - Affected Robot Software Version(s): 3.7
 - Affected Robot Hardware Version(s): UR3
 - URCaps Software version(s): 1.0.5

**Comment by fmauch** [comment]
- Did you setup the URCap with the correct remote IP address as described [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/install_urcap_cb3.md) / Is 192.160.0.100 the IP address of your machine running the ROS driver?
- Did you start the ROS driver before starting the program on the TP?

Anyway, this should not block forever, I'll try to reproduce this.

**Comment by fmauch** [comment]
I've never been able to reproduce this and there has never been a follow-up answer, so I'll close this. Feel free to comment / reopen if the issue still persists.
