### ISSUE TITLE
Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]

### ISSUE THREAD

**Issue by robint-XNF** [UniversalRobots/Universal_Robots_ROS_Driver#353]
i have a real ur3 robot,controller type is CB3. 
when i run `roslaunch ur_robot_driver ur3_bringup.launch`
and `roslaunch ur3_moveit_coonfig demo.launch`
i try to excute the real robot ,and then the error :
Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]

**Comment by fmauch** [comment]
Did my answer in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/55#issuecomment-830640815 help?

**Comment by stefanscherzinger** [comment]
Feel free to re-open if this issue persists.
