### ISSUE TITLE
[ros_control_controller_manager-5] process has finished cleanly

### ISSUE THREAD

**Issue by Neowenwen** [UniversalRobots/Universal_Robots_ROS_Driver#36]
### roslaunch ur_robot_driver ur5e_bringup.launch robot_ip:=192.168.1.10
I have this problem：[ros_control_controller_manager-5] process has finished cleanly

roslaunch ur_robot_driver ur5e_bringup.launch robot_ip:=192.168.1.10
... logging to /home/z/.ros/log/4c9d4a9a-05e5-11ea-b66c-00e04c515af0/roslaunch-z-l-2939.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://z-l:39581/

SUMMARY
========

PARAMETERS
 * /controller_stopper/consistent_controllers: ['joint_state_con...
 * /force_torque_sensor_controller/publish_rate: 500
 * /force_torque_sensor_controller/type: force_torque_sens...
 * /hardware_control_loop/loop_hz: 500
 * /hardware_interface/joints: ['shoulder_pan_jo...
 * /joint_state_controller/publish_rate: 500
 * /joint_state_controller/type: joint_state_contr...
 * /pos_traj_controller/action_monitor_rate: 10
 * /pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /pos_traj_controller/constraints/elbow_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/goal_time: 0.6
 * /pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
 * /pos_traj_controller/joints: ['shoulder_pan_jo...
 * /pos_traj_controller/state_publish_rate: 500
 * /pos_traj_controller/stop_trajectory_duration: 0.5
 * /pos_traj_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /scaled_pos_traj_controller/action_monitor_rate: 10
 * /scaled_pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/elbow_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/goal_time: 0.6
 * /scaled_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /scaled_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/joints: ['shoulder_pan_jo...
 * /scaled_pos_traj_controller/state_publish_rate: 500
 * /scaled_pos_traj_controller/stop_trajectory_duration: 0.5
 * /scaled_pos_traj_controller/type: position_controll...
 * /speed_scaling_state_controller/publish_rate: 500
 * /speed_scaling_state_controller/type: ur_controllers/Sp...
 * /ur_hardware_interface/headless_mode: False
 * /ur_hardware_interface/input_recipe_file: /home/z/ur_ws/src...
 * /ur_hardware_interface/kinematics/forearm/pitch: 3.14017199916
 * /ur_hardware_interface/kinematics/forearm/roll: 3.14059068755
 * /ur_hardware_interface/kinematics/forearm/x: -0.425037893955
 * /ur_hardware_interface/kinematics/forearm/y: 0
 * /ur_hardware_interface/kinematics/forearm/yaw: -3.14158816371
 * /ur_hardware_interface/kinematics/forearm/z: 0
 * /ur_hardware_interface/kinematics/hash: calib_39802185810...
 * /ur_hardware_interface/kinematics/shoulder/pitch: 0
 * /ur_hardware_interface/kinematics/shoulder/roll: 0
 * /ur_hardware_interface/kinematics/shoulder/x: 0
 * /ur_hardware_interface/kinematics/shoulder/y: 0
 * /ur_hardware_interface/kinematics/shoulder/yaw: 7.37238859683e-08
 * /ur_hardware_interface/kinematics/shoulder/z: 0.162324408873
 * /ur_hardware_interface/kinematics/upper_arm/pitch: 0
 * /ur_hardware_interface/kinematics/upper_arm/roll: 1.56992930797
 * /ur_hardware_interface/kinematics/upper_arm/x: 4.84366363075e-05
 * /ur_hardware_interface/kinematics/upper_arm/y: 0
 * /ur_hardware_interface/kinematics/upper_arm/yaw: 6.15937720869e-06
 * /ur_hardware_interface/kinematics/upper_arm/z: 0
 * /ur_hardware_interface/kinematics/wrist_1/pitch: -3.14098620009
 * /ur_hardware_interface/kinematics/wrist_1/roll: 3.13502703346
 * /ur_hardware_interface/kinematics/wrist_1/x: -0.392221657252
 * /ur_hardware_interface/kinematics/wrist_1/y: 0.000875846517558
 * /ur_hardware_interface/kinematics/wrist_1/yaw: 3.14158797796
 * /ur_hardware_interface/kinematics/wrist_1/z: 0.133396985332
 * /ur_hardware_interface/kinematics/wrist_2/pitch: 0
 * /ur_hardware_interface/kinematics/wrist_2/roll: 1.57058704786
 * /ur_hardware_interface/kinematics/wrist_2/x: 2.50023335042e-05
 * /ur_hardware_interface/kinematics/wrist_2/y: -0.0996555417782
 * /ur_hardware_interface/kinematics/wrist_2/yaw: -3.85827428446e-07
 * /ur_hardware_interface/kinematics/wrist_2/z: 2.08558061508e-05
 * /ur_hardware_interface/kinematics/wrist_3/pitch: 3.14159265359
 * /ur_hardware_interface/kinematics/wrist_3/roll: 1.57146277288
 * /ur_hardware_interface/kinematics/wrist_3/x: 0.00010963338722
 * /ur_hardware_interface/kinematics/wrist_3/y: 0.0993621411081
 * /ur_hardware_interface/kinematics/wrist_3/yaw: 3.1415923712
 * /ur_hardware_interface/kinematics/wrist_3/z: 6.62195197273e-05
 * /ur_hardware_interface/output_recipe_file: /home/z/ur_ws/src...
 * /ur_hardware_interface/robot_ip: 192.168.1.10
 * /ur_hardware_interface/script_file: /home/z/ur_ws/src...
 * /ur_hardware_interface/tf_prefix: 
 * /ur_hardware_interface/tool_baud_rate: 115200
 * /ur_hardware_interface/tool_parity: 0
 * /ur_hardware_interface/tool_rx_idle_chars: 1.5
 * /ur_hardware_interface/tool_stop_bits: 1
 * /ur_hardware_interface/tool_tx_idle_chars: 3.5
 * /ur_hardware_interface/tool_voltage: 0
 * /ur_hardware_interface/use_tool_communication: False

NODES
  /
    controller_stopper (controller_stopper/node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    ros_control_controller_manager (controller_manager/controller_manager)
    ros_control_controller_spawner (controller_manager/spawner)
    ur_hardware_interface (ur_robot_driver/ur_robot_driver_node)
  /ur_hardware_interface/
    ur_robot_state_helper (ur_robot_driver/robot_state_helper)

auto-starting new master
process[master]: started with pid [2952]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4c9d4a9a-05e5-11ea-b66c-00e04c515af0
process[rosout-1]: started with pid [2965]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [2982]
process[ur_hardware_interface-3]: started with pid [2983]
process[ros_control_controller_spawner-4]: started with pid [2985]
process[ros_control_controller_manager-5]: started with pid [2998]
[ INFO] [1573629299.827127349]: Main thread: SCHED_FIFO OK
[ INFO] [1573629299.827224498]: Main thread priority is 99
process[controller_stopper-6]: started with pid [3011]
[ INFO] [1573629299.856995085]: Initializing dashboard client
[ INFO] [1573629299.859225064]: Connected: Universal Robots Dashboard Server

process[ur_hardware_interface/ur_robot_state_helper-7]: started with pid [3048]
[ INFO] [1573629299.940176571]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1573629299.942043881]: Initializing urdriver
[ INFO] [1573629299.942540373]: Checking if calibration data matches connected robot.
[ INFO] [1573629299.943060817]: Producer thread: SCHED_FIFO OK
[ INFO] [1573629299.943125984]: Thread priority is 99
[ INFO] [1573629299.944610438]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[ INFO] [1573629300.393358835]: Calibration checked successfully.
[INFO] [1573629300.399231]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1573629300.998313419]: Producer thread: SCHED_FIFO OK
[ INFO] [1573629300.998365004]: Thread priority is 99
[ INFO] [1573629301.552251860]: Setting up RTDE communication with frequency 500.000000
[ INFO] [1573629302.572216855]: Producer thread: SCHED_FIFO OK
[ INFO] [1573629302.572281891]: Thread priority is 99
[ INFO] [1573629302.572373621]: Loaded ur_robot_driver hardware_interface
[ INFO] [1573629302.636417281]: waitForService: Service [/controller_manager/switch_controller] is now available.
[ INFO] [1573629302.636481087]: Service available.
[ INFO] [1573629302.636555653]: Waiting for controller list service to come up on /controller_manager/list_controllers
[ INFO] [1573629302.638067905]: Service available.
[ INFO] [1573629302.822312359]: Robot's safety mode is now NORMAL
[ INFO] [1573629302.822703305]: Robot mode is now RUNNING
[INFO] [1573629302.824334]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1573629302.826584]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1573629302.828637]: Loading controller: joint_state_controller
[INFO] [1573629302.844996]: Loading controller: scaled_pos_traj_controller
Loaded pos_traj_controller
[INFO] [1573629302.994883]: Loading controller: speed_scaling_state_controller
[INFO] [1573629303.002823]: Loading controller: force_torque_sensor_controller
[INFO] [1573629303.014036]: Controller Spawner: Loaded controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[INFO] [1573629303.018860]: Started controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[ros_control_controller_manager-5] process has finished cleanly
log file: /home/z/.ros/log/4c9d4a9a-05e5-11ea-b66c-00e04c515af0/ros_control_controller_manager-5*.log

What should I do?

**Comment by fmauch** [comment]
This is totally fine as this manager is just spawning controllers. We could, however, name them differently and use the actual spawner to avoid confusion in the future.
