### ISSUE TITLE
i can't connect PC (Ubuntu 18.04) to UR3(CB3 3.7)

### ISSUE THREAD

**Issue by KhuuLuanThanh** [UniversalRobots/Universal_Robots_ROS_Driver#364]
i try to connect UR3 robot with PC Vmware Ubuntu 18.04(ROS melodic)
i use external control 1.05.urcap and setup successful in CB3 ( v3.7).
IP PC ROS: 192.168.0.128 and IP robot 192.168.0.161   2 IP works normally.
But when i run: 
roslaunch ur_robot_driver ur3_bringup.launch robot_ip:=192.168.0.161
an error occurred like image.
i follow tutorial in ROS.wiki and this page but can't do it.
Thanks. wish you a nice day!
![182973149_470999487510626_9174922883411806011_n](https://user-images.githubusercontent.com/83744895/117534853-5dd96300-b01d-11eb-942f-b8cbc43c5a53.jpg)
![Capture](https://user-images.githubusercontent.com/83744895/117534960-d3ddca00-b01d-11eb-975b-4b33d7a3cdfb.jpg)

**Comment by urrsk** [comment]
It sounds like a connection issue.
Can you verify that you can  ```ping``` the robot from the ROS side as well as ```ping``` the ROS ip from the robot side?

**Comment by KhuuLuanThanh** [comment]
It my problem!
This is image Network i setup to Robot
![2](https://user-images.githubusercontent.com/83744895/117629256-2ea12e00-b1a4-11eb-92a7-ff063d21c5ac.jpg)
( the network is connected)

But on terminal Ubuntu:
 I command: ping 192.168.0.100
It like this
![3](https://user-images.githubusercontent.com/83744895/117629486-6a3bf800-b1a4-11eb-8c0b-58d9382988a2.jpg)

I use Vmware Ubuntu 18.04 and Wifi. And this is the way i use Ethernet cap connect PC with CB3.
![1](https://user-images.githubusercontent.com/83744895/117629820-be46dc80-b1a4-11eb-94b8-e2ea11cd081d.jpg)

is it the problem my network or my way connect PC and CB3?
Wish you have a nice day.

**Comment by fmauch** [comment]
Clearly, there seems to be an error in your network setup.

First of all, please use [code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for any shell interaction, this makes it a lot more readable than screenshots.

Second, let's find out your network setup.

`ip addr` should print all configured network interfaces. For your setup to work, I would expect that there would be an interface in the same subnet as the robot machine.

As you are running ubuntu inside a VM (which I would not recommend for performance reasons), you'll have to make sure that your physical network connector is available inside the VM. Then, in your VM make sure to [setup a manual IP address](https://linuxize.com/post/how-to-configure-static-ip-address-on-ubuntu-18-04/#configuring-static-ip-address-on-ubuntu-desktop) that is in the same subnet as your robot controller, e.g. `192.168.0.42`

When this is setup correctly, you should be able to execute `ping 192.168.0.100` correctly.

**Comment by KhuuLuanThanh** [comment]
@fmauch @urrsk Thanks for your help so much!
Today i can connect with my robot! it my error about setup network!
Wish you have a nice day!

**Comment by fmauch** [comment]
I'll mark this resolved, then. Glad to hear it is working now.
