### ISSUE TITLE
How can I limit velocity in program?

### ISSUE THREAD

**Issue by Ryoga723** [UniversalRobots/Universal_Robots_ROS_Driver#374]
Hello,

When we use UR, we can limit its velocity by teach pendant.

But it's stupid to manipulate teach pendant every time.

So I'd like to change limitation in moveit program.

Now I use moveit::planning_interface::MoveGroupInterface move_group class and to execute move_group.execute(my plan) is method to move robot.

Thank you for your helping.

**Comment by fmauch** [comment]
Please see the [set_speed_slider](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/ROS_INTERFACE.md#set_speed_slider-ur_msgssetspeedsliderfraction) service if you'd like to adapt the velocity on-the-fly.

However, moveit does also provide methods to set a trajectory's velocity as a percentage of full speed. It has the field [`max_velocity_scaling_factor`](http://docs.ros.org/en/api/moveit_msgs/html/msg/MotionPlanRequest.html).

Does this answer your question?
