### ISSUE TITLE
Does this driver  ur_robot_drive has any similar functions as  the " /joint_speed " in ur_modern_driver ?

### ISSUE THREAD

**Issue by sunnymints** [UniversalRobots/Universal_Robots_ROS_Driver#378]
Does this driver  ur_robot_drive has any similar functions as  the " /joint_speed " in ur_modern_driver ?
    I  attempt to use joint_group_vel_controller in ur_robot_drive to realize function " /joint_speed " in ur_modern_driver  but the effect was not ideal.

**Comment by fmauch** [comment]
I don't know by heart what the functionality in the `ur_modern_driver` behind the `/joint_speed` topic was. If you could provide a reference to the matching source code inside the `ur_modern_driver` it might be easier to answer that question.
