### ISSUE TITLE
ros dependency problem

### ISSUE THREAD

**Issue by seunghwa9118** [UniversalRobots/Universal_Robots_ROS_Driver#384]
# Summary
I enter on terminer : rosdep install --from-paths src --ignore-src -y
and I got error
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ur_calibration: Cannot locate rosdep definition for [ur_client_library]
ur_robot_driver: Cannot locate rosdep definition for [ur_msgs]

How can i fix it?

# Versions
 - ROS Driver version: kinetic+ 16.04 ubuntu

![스크린샷, 2021-05-23 00-10-17](https://user-images.githubusercontent.com/68892551/119231409-b2232d80-bb5b-11eb-9d0e-ba4582a56d49.png)

**Comment by Ashok93** [comment]
I had the same issue. Using `RUN rosdep update --include-eol-distros` fixed it.

**Comment by lianghongzhuo** [comment]
The new universal_robot repo: https://github.com/fmauch/universal_robot/tree/calibration_devel
deleted ur_msgs package.

So you can install it by yourself `git clone https://github.com/ros-industrial/ur_msgs.git`

**Comment by lianghongzhuo** [comment]
This is needed if you are using noetic, as `ur_msgs` didn't release at noetic version

**Comment by seunghwa9118** [comment]
> The new universal_robot repo: https://github.com/fmauch/universal_robot/tree/calibration_devel
> deleted ur_msgs package.
> 
> So you can install it by yourself `git clone https://github.com/ros-industrial/ur_msgs.git`

thank you i fixed it. i just write on the terminal git clone https://github.com/ros-industrial/ur_msgs.git

**Comment by seunghwa9118** [comment]
> rosdep update --include-eol-distros

thank you i fixed it

**Comment by fmauch** [comment]
I think, this is fixed with #387. Also `ur_msgs` is on the way for ROS noetic. Therefore, I'm closing this.
