### ISSUE TITLE
 error: ‘ur_msgs::SetPayload::Request {aka struct ur_msgs::SetPayloadRequest_<std::allocator<void> >}’ has no member named ‘center_of_gravity’

### ISSUE THREAD

**Issue by seunghwa9118** [UniversalRobots/Universal_Robots_ROS_Driver#385]
# Summary

I doing catkin_make and got error in this picture. how can i fix it?

*Introduction to the issue*

# Versions
 - ROS Driver version: 16.04 ubuntu + kinetic
 
![스크린샷, 2021-05-23 02-29-24](https://user-images.githubusercontent.com/68892551/119235682-b86ed500-bb6e-11eb-8289-c4ae94f3624c.png)

**Comment by lianghongzhuo** [comment]
The new universal_robot repo: https://github.com/fmauch/universal_robot/tree/calibration_devel
deleted ur_msgs package.
Maybe we should add something in the readme?
Like:
`git clone https://github.com/ros-industrial/ur_msgs.git`

**Comment by fmauch** [comment]
the `rosdep install` command should make sure to install all necessary dependencies including `ur_msgs`

**Comment by stefanscherzinger** [comment]
This has been addressed by #387 and is now in the documentation.
