### ISSUE TITLE
Submit repository for documentation indexing

### ISSUE THREAD

**Issue by gavanderhoorn** [UniversalRobots/Universal_Robots_ROS_Driver#41]
Would it be an idea to submit this repository to `ros/rosdistro` for indexing by the ROS buildfarm?

Having a `doc` job would be nice for the newly created [wiki page](http://wiki.ros.org/ur_robot_driver).

**Comment by fmauch** [comment]
Sure! I was not aware that I could index a package for documentation only.

**Comment by fmauch** [comment]
https://github.com/ros/rosdistro/pull/23107

**Comment by gavanderhoorn** [comment]
Seems ros/rosdistro#23107 got merged.

Closing.

Thanks @fmauch  :+1:
