### ISSUE TITLE
Is there any command to reset force sensor?

### ISSUE THREAD

**Issue by Ryoga723** [UniversalRobots/Universal_Robots_ROS_Driver#414]
Hello.

I use UR5e and its default force sensor which can be referenced as /wrench topic in ROS.
When I tap joint position button and ok button, the force sensor value is reset to zero maybe.

I don't know this is specification of Universal Robot.
Can I reset the force sensor in my program? For example, by sending action command.

Thank you for your helping.

**Comment by fmauch** [comment]
Does [this service](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/ROS_INTERFACE.md#zero_ftsensor-std_srvstrigger) help?

**Comment by Ryoga723** [comment]
Thank you for your answering!
