### ISSUE TITLE
Some mistakes about Gazebo

### ISSUE THREAD

**Issue by gyxx323** [UniversalRobots/Universal_Robots_ROS_Driver#419]
# Versions
 - ROS Driver version:Universal_Robots_ROS_Driver
 - ubuntu18.04+ros melodic
 - fmauch_universal_robot（calibration_devel）

# Problem
I downloaded files from https://github.com/fmauch/universal_robot/tree/calibration_devel, and want to use for the calculation of the gazebo.
But when I run the command
`roslaunch ur_gazebo ur3.launch`
It will report an error that the file ur3.launch does not exist

Then I found a file called ur3_bringup.launch in the ur_gazebo folder and I ran 
`roslaunch ur_gazebo ur3_bringup.launch`
The Gazebo interface will start, but I'll get an error when I try to start the RVIZ interface in subsequent runs. Model image is not loaded in the RVIZ interface.

I think there is something wrong with my Gazebo. Can I use ur3_bringup.launch instead of ur3. Launch? If not, what should I do?
Thank you!

**Comment by fmauch** [comment]
This is not related to anything in this driver. Please reopen this issue at https://github.com/fmauch/universal_robot/issues
