### ISSUE TITLE
suddenly controller error

### ISSUE THREAD

**Issue by robint-XNF** [UniversalRobots/Universal_Robots_ROS_Driver#424]

**Comment by robint-XNF** [comment]
i try to use a remote computer to control ur, however, when i use " rosrun rqt_joint_trajectory_controller rqt_joint_trajectory_controller", the error shows "Unable to communicate with service [/controller_manager/load_controller], address [rosrpc://192.168.199.190:36791]"

**Comment by gavanderhoorn** [comment]
If you solved your problem, could you please post the solution and not remove the original question/report?

That would help future users if they ever encounter the same problem.
