### ISSUE TITLE
How can I distinguish two robot's /tf information?

### ISSUE THREAD

**Issue by Ryoga723** [UniversalRobots/Universal_Robots_ROS_Driver#428]
Hello!

Now I control two UR robots connected by ROS.
The method of connection is grouping by launch file.

Then each topics are distinguished by group names, but /tf information is not distinguished.
That's why two /tf tree is displayed alternately in my rviz screen.
I would like to check two robot's /tf information at the same time to debug.

How can I distinguish two robot's /tf information ?
Please teach me just keywords if you know anything. Thank you for your helping.

**Comment by fmauch** [comment]
#81 covers this quite intensively, which is why I would close this issue, if that's ok with you. There's also #358 where I'd like to create proper documentation for this. I you like, you could contribute to that while solving your use case while you are learning how to tackle this.
