### ISSUE TITLE
Can't connect UR3e with PC

### ISSUE THREAD

**Issue by Csp0920** [UniversalRobots/Universal_Robots_ROS_Driver#43]
# Summary
I am trying to connect PC with UR3e. Following the tutorials, I can't realize the connection.
There are two problems:
1.Running "roslaunch ur3_e_bringup.launch" error.
2.When run URCaps in the Tech Pendant, it showed "The connection to the remote PC could not be established".

# Versions
 - ROS Driver version:Kinetic+ubuntu16.04
 - Affected Robot Software Version(s): 5.3 for UR3e

# Issue details
I downloaded the ROS-Industrial Universal Robot meta-package and Universal_Robots_ROS_Driver. Then I followed the steps and installed URCaps, but I skipped real-time kernel.

After doing catkin_make and source...., I run "roslaunch ur_robot_driver ur3e_bringup.launch robot_ip:=192.168.56.1", the results are as follow:

[ INFO] [1574245554.735175067]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1574245554.738353661]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[ INFO] [1574245554.793670178]: Initializing urdriver
[ INFO] [1574245554.793960708]: Checking if calibration data matches connected robot.
[ WARN] [1574245554.794206654]: No realtime capabilities found. Consider using a realtime system for better performance
[INFO] [1574245554.992951]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1574245554.996650]: Controller Spawner: Waiting for service controller_manager/load_controller
[ERROR] [1574245555.255396778]: The calibration parameters of the connected robot don't match the ones from the given kinematics config file. Please be aware that this can lead to critical inaccuracies of tcp positions. Use the ur_calibration tool to extract the correct calibration from the robot and pass that into the description. See [TODO Link to documentation] for details.
[ WARN] [1574245555.858848371]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1574245556.319504210]: Setting up RTDE communication with frequency 500.000000
[ WARN] [1574245557.365727189]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1574245557.365899298]: Loaded ur_robot_driver hardware_interface
[ INFO] [1574245557.414367666]: waitForService: Service [/controller_manager/switch_controller] is now available.
[ INFO] [1574245557.414430813]: Service available.
[ INFO] [1574245557.414475567]: Waiting for controller list service to come up on /controller_manager/list_controllers
[ INFO] [1574245557.415821403]: Service available.
[INFO] [1574245557.419021]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1574245557.421578]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1574245557.422596]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1574245557.423761]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1574245557.425062]: Loading controller: joint_state_controller
[INFO] [1574245557.427147]: Loading controller: pos_traj_controller
[INFO] [1574245557.435428]: Loading controller: scaled_pos_traj_controller
[INFO] [1574245557.479396]: Controller Spawner: Loaded controllers: pos_traj_controller
[INFO] [1574245557.523175]: Loading controller: speed_scaling_state_controller
[INFO] [1574245557.529331]: Loading controller: force_torque_sensor_controller
[INFO] [1574245557.537934]: Controller Spawner: Loaded controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[INFO] [1574245557.541387]: Started controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[ INFO] [1574245557.636512869]: Robot's safety mode is now NORMAL
[ INFO] [1574245557.636817392]: Robot mode is now RUNNING
^C[ur_hardware_interface/ur_robot_state_helper-6] killing on exit
[controller_stopper-5] killing on exit
[ros_control_stopped_spawner-4] killing on exit
[ros_control_controller_spawner-3] killing on exit
[ur_hardware_interface-2] killing on exit
[robot_state_publisher-1] killing on exit
Interrupt signal (2) received.
[INFO] [1574245629.356163]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1574245629.356365]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1574245629.356777]: Stopping all controllers...
[INFO] [1574245629.356897]: Stopping all controllers...
[ERROR] [1574245629.361387907]: Could not stop controller 'scaled_pos_traj_controller' since it is not running
[INFO] [1574245629.361688]: Unloading all loaded controllers...
[ERROR] [1574245629.361949202]: Could not stop controller 'pos_traj_controller' since it is not running
[INFO] [1574245629.362129]: Trying to unload force_torque_sensor_controller
[INFO] [1574245629.362238]: Unloading all loaded controllers...
[INFO] [1574245629.362596]: Trying to unload pos_traj_controller
terminate called without an active exception
[WARN] [1574245629.533725]: Controller Spawner error while taking down controllers: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] [1574245629.533726]: Controller Spawner error while taking down controllers: transport error completing service call: unable to receive data from sender, check sender's logs for details
shutting down processing monitor...
... shutting down processing monitor complete
done

And I tried to press the run bottom in the Tech Pendant, it showed "The connection to the remote PC could not be established".

I didn't change any configuration in the package. If there were something that needed to modify?

The External Control Host IP:192.168.56.1
UR3e IP: 192.168.56.1
My computer IP: 192.168.56.2
I don't know if my settings are correct, so I showed them.

Hoping for your response. Sorry for disturbing you.  And thank you very much.

**Comment by gavanderhoorn** [comment]
> Running "roslaunch ur3_e_bringup.launch" error.

The console log you include shows you pressing <kbd>ctrl</kbd>+<kbd>c</kbd> right after the driver reports:

```
[ INFO] [1574245557.636817392]: Robot mode is now RUNNING
```

up until that point there doesn't appear to be any problem.

It would seem to make sense for the External Control on the robot controller to complain it can't connect to the PC if you've just shut everything down.

**Comment by Csp0920** [comment]
@gavanderhoorn  I‘m sorry that I didn't get your points.

**Comment by gavanderhoorn** [comment]
The log you show, has this:

```
[ INFO] [1574245557.636512869]: Robot's safety mode is now NORMAL
[ INFO] [1574245557.636817392]: Robot mode is now RUNNING
^C[ur_hardware_interface/ur_robot_state_helper-6] killing on exit
[controller_stopper-5] killing on exit
[ros_control_stopped_spawner-4] killing on exit
[ros_control_controller_spawner-3] killing on exit
[ur_hardware_interface-2] killing on exit
[robot_state_publisher-1] killing on exit
Interrupt signal (2) received.
```

that seems to suggest you pressed <kbd>ctrl</kbd>+<kbd>c</kbd> at some point (note the `^C`).

Why did you press <kbd>ctrl</kbd>+<kbd>c</kbd>?

From the output it would seem the driver was started OK, with no errors. At least on the ROS side.

**Comment by Csp0920** [comment]
@gavanderhoorn  The program stays at:
[ INFO] [1574245557.636512869]: Robot's safety mode is now NORMAL
[ INFO] [1574245557.636817392]: Robot mode is now RUNNING

And then I press the run bottom in the Tech Pendant, it showed "The connection to remote PC could not be established".

So I press ctrl+c

**Comment by gavanderhoorn** [comment]
> The External Control Host IP:192.168.56.1
UR3e IP: 192.168.56.1
My computer IP: 192.168.56.2

As mentioned in the [e-series setup guide](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/install_urcap_e_series.md), you should enter the IP of the "external PC which will be running the ROS driver" on the *External Control* setup screen.

In your case that would seem to be `192.168.56.2`, not `192.168.56.1` (as that would be the robot's IP address).

**Comment by Csp0920** [comment]
@gavanderhoorn  I see what you mean. So i need to make the ip of PC and External Control same.  I will try it tomorrow.

**Comment by Csp0920** [comment]
@gavanderhoorn  Thank you for you patient reponse.

**Comment by Csp0920** [comment]
@gavaderhoorn @fmauch 
Thanks for your help. Now I can successfully connect my pc with ur3e.
I change the ip from 192.168.56.x to 192.168.1.x. Then it succeed. 
Sorry that I didn't reply in time, and really thanks for your help.

**Comment by tt2cloud** [comment]
Hello, brother,I recently encountered a same problem.I am trying to connect PC with UR10e. Following the tutorials, I don't able to the UR10e.I downloaded (https://github.com/UniversalRobots/Universal_Robots_ROS_Driver.git src/Universal_Robots_ROS_Driver) and (https://github.com/fmauch/universal_robot.git src/fmauch_universal_robot) two packages, when I was connecting the PC IP

termial1:roslaunch ur_robot_driver ur10e_bringup.launch
auto-starting new master
process[master]: started with pid [16046]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f9f4466a-aaf6-11ea-87df-c8d9d21823f2
process[rosout-1]: started with pid [16063]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [16080]
process[ur_hardware_interface-3]: started with pid [16081]
process[ros_control_controller_spawner-4]: started with pid [16082]
[ INFO] [1591778833.244461464]: Main thread: SCHED_FIFO OK
[ INFO] [1591778833.244515999]: Main thread priority is 99
process[ros_control_stopped_spawner-5]: started with pid [16097]
[ INFO] [1591778833.254436740]: Initializing dashboard client
[ INFO] [1591778833.259312031]: Connected: Universal Robots Dashboard Server

process[controller_stopper-6]: started with pid [16133]
process[ur_hardware_interface/ur_robot_state_helper-7]: started with pid [16151]
[ INFO] [1591778833.279400014]: Initializing urdriver
[ INFO] [1591778833.279905846]: Checking if calibration data matches connected robot.
[ INFO] [1591778833.280442042]: Producer thread: SCHED_FIFO OK
[ INFO] [1591778833.280469870]: Thread priority is 99
[ INFO] [1591778833.286314783]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1591778833.287298633]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[ERROR] [1591778833.342191180]: The calibration parameters of the connected robot don't match the ones from the given kinematics config file. Please be aware that this can lead to critical inaccuracies of tcp positions. Use the ur_calibration tool to extract the correct calibration from the robot and pass that into the description. See [TODO Link to documentation] for details.
[INFO] [1591778833.634791]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1591778833.691968]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1591778834.345545407]: Producer thread: SCHED_FIFO OK
[ INFO] [1591778834.345570416]: Thread priority is 99
[ INFO] [1591778834.389224845]: Setting up RTDE communication with frequency 500.000000
[FATAL] [1591778835.405016530]: Variable 'speed_slider_mask' is currently controlled by another RTDE client. The input recipe can't be used as configured
[ERROR] [1591778835.405094844]: Could not correctly initialize robot. Exiting
================================================================================REQUIRED process [ur_hardware_interface-3] has died!
process has died [pid 16081, exit code 1, cmd /home/yun/catkin_ws7/devel/lib/ur_robot_driver/ur_robot_driver_node __name:=ur_hardware_interface __log:=/home/yun/.ros/log/f9f4466a-aaf6-11ea-87df-c8d9d21823f2/ur_hardware_interface-3.log].
log file: /home/yun/.ros/log/f9f4466a-aaf6-11ea-87df-c8d9d21823f2/ur_hardware_interface-3*.log
Initiating shutdown!
================================================================================
[ur_hardware_interface/ur_robot_state_helper-7] killing on exit
[controller_stopper-6] killing on exit
[ros_control_stopped_spawner-5] killing on exit
[ros_control_controller_spawner-4] killing on exit
[ur_hardware_interface-3] killing on exit
[robot_state_publisher-2] killing on exit
[WARN] [1591778835.978961]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1591778835.978991]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[controller_stopper-6] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
terminal2:roslaunch ur10_e_moveit_config ur10_e_moveit_planning_execution.launch limited:=true
SUMMARY
========

PARAMETERS
 * /move_group/allow_trajectory_execution: True
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'action_ns': 'f...
 * /move_group/endeffector/planner_configs: ['SBLkConfigDefau...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/manipulator/default_planner_config: RRTConnectkConfig...
 * /move_group/manipulator/longest_valid_segment_fraction: 0.01
 * /move_group/manipulator/planner_configs: ['SBLkConfigDefau...
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/execution_duration_monitoring: False
 * /move_group/use_controller_manager: False
 * /robot_description_kinematics/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/manipulator/kinematics_solver_attempts: 3
 * /robot_description_kinematics/manipulator/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/elbow_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/elbow_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/elbow_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/elbow_joint/max_velocity: 3.14
 * /robot_description_planning/joint_limits/shoulder_lift_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/shoulder_lift_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/shoulder_lift_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/shoulder_lift_joint/max_velocity: 3.14
 * /robot_description_planning/joint_limits/shoulder_pan_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/shoulder_pan_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/shoulder_pan_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/shoulder_pan_joint/max_velocity: 3.14
 * /robot_description_planning/joint_limits/wrist_1_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/wrist_1_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_1_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/wrist_1_joint/max_velocity: 6.28
 * /robot_description_planning/joint_limits/wrist_2_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/wrist_2_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_2_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/wrist_2_joint/max_velocity: 6.28
 * /robot_description_planning/joint_limits/wrist_3_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/wrist_3_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_3_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/wrist_3_joint/max_velocity: 6.28
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    move_group (moveit_ros_move_group/move_group)

ROS_MASTER_URI=http://localhost:11311

run_id on parameter server does not match declared run_id: f9f4466a-aaf6-11ea-87df-c8d9d21823f2 vs fa6e0978-aaf6-11ea-87df-c8d9d21823f2
The traceback for the exception was written to the log file
termial3:roslaunch ur10_e_moveit_config moveit_rviz.launch 
SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver_attempts: 3
 * /rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver_search_resolution: 0.005
 * /rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver_timeout: 0.005

NODES
  /
    rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018 (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018-1]: started with pid [16294]
[ INFO] [1591778834.186943878]: rviz version 1.12.17
[ INFO] [1591778834.187022497]: compiled against Qt version 5.5.1
[ INFO] [1591778834.187047235]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1591778834.483021439]: Stereo is NOT SUPPORTED
[ INFO] [1591778834.483084141]: OpenGl version: 3 (GLSL 1.3).
[ERROR] [1591778835.330058916]: Robot semantic description not found. Did you forget to define or remap '/robot_description_semantic'?
[ INFO] [1591778835.330242282]: Loading robot model 'ur10e'...
[ INFO] [1591778835.330292133]: No root/virtual joint specified in SRDF. Assuming fixed joint
The TP show don't connect to the remote PC establish.
Could you help me ,this question has really been bothering me, thanks advance!@fmauch@Csp0920

**Comment by gavanderhoorn** [comment]
@tt2cloud: your issue is different (note the RTDE problem reported by the driver).

I would recommend you post it in a new issue.

@fmauch: I've seen this mentioned in PickNikRobotics/picknik_ur5_moveit_config#9 as well.

**Comment by tt2cloud** [comment]
> @tt2cloud: your issue is different (note the RTDE problem reported by the driver).
> 
> I would recommend you post it in a new issue.
> 
> @fmauch: I've seen this mentioned in [PickNikRobotics/picknik_ur5_moveit_config#9](https://github.com/PickNikRobotics/picknik_ur5_moveit_config/pull/9) as well.

brother, thank you reply.

**Comment by gavanderhoorn** [comment]
> brother, thank you reply.

Please don't call me that.

**Comment by tt2cloud** [comment]
Hi～ brother,can you help me solve the problem ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;G.A.&amp;nbsp;vd.&amp;nbsp;Hoorn&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月10日(星期三) 下午5:28
收件人:&nbsp;&quot;UniversalRobots/Universal_Robots_ROS_Driver&quot;<Universal_Robots_ROS_Driver@noreply.github.com&gt;;
抄送:&nbsp;&quot;tt2cloud&quot;<1091350626@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [UniversalRobots/Universal_Robots_ROS_Driver] Can&#39;t connect UR3e with PC (#43)

**Comment by tt2cloud** [comment]
> @tt2cloud: your issue is different (note the RTDE problem reported by the driver).
> 
> I would recommend you post it in a new issue.
> 
> @fmauch: I've seen this mentioned in [PickNikRobotics/picknik_ur5_moveit_config#9](https://github.com/PickNikRobotics/picknik_ur5_moveit_config/pull/9) as well.

Hi,brother,Do I need to modify the code, if it needs to be modified, please tell me how to modify it,because I don’t understand it too much,thank you very much!

**Comment by fmauch** [comment]
@tt2cloud  I'd also appreciate if you'd open a new issue and if you would kindly stop, calling anybody "brother" here. Thanks.

**Comment by tt2cloud** [comment]
> @tt2cloud I'd also appreciate if you'd open a new issue and if you would kindly stop, calling anybody "brother" here. Thanks.

Hi,I am so glad you can answer my questions, I am a chinese student.
I open a new issue that describes my operation steps and settings[(https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/191)]
So, I hope you can answer this question
