### ISSUE TITLE
Problems connecting to UR5e with ur_robot_driver

### ISSUE THREAD

**Issue by danyHAD** [UniversalRobots/Universal_Robots_ROS_Driver#441]
# Impact

Hello! I cannot connect completely to the robot. I followed the required steps in order to connect to the robot. I run the driver on ros, then I run the external control program from the teach pendant on the robot and everything seems alright, yet I only receive these messages:

[ INFO] [1627295507.279741482]: Robot requested program
[ INFO] [1627295507.279906055]: Sent program to robot

And I never receive the "Robot ready to receive commands." message, thus I don't have full access to the robot from ROS.

I've attached the script, .urp and .installation files which are used by the robot here: https://easyupload.io/qnwng4

**Comment by fmauch** [comment]
is this a cross-post of https://answers.ros.org/question/383307/problems-connecting-to-ur5e-robot/? If so, let's stick to the ROS answers thread as we have been discussing things there, already.
