### ISSUE TITLE
In the hardware_interface, some members should be atomic

### ISSUE THREAD

**Issue by AndyZe** [UniversalRobots/Universal_Robots_ROS_Driver#447]
It seems like `robot_program_running_` and `controller_reset_necessary_` should be std::atomic<bool> type for thread safety. I say this because it looks like there is potential to read the variables at the same time as writing them from a callback.

Maybe others as well, like `position_controller_running_` and `velocity_controller_running_`

**Comment by fmauch** [comment]
Thanks for bringing this up. We will definitely look into this!

**Comment by fmauch** [comment]
This  has been fixed in #448 -> closing
