### ISSUE TITLE
Jittery Motion of UR5e

### ISSUE THREAD

**Issue by nitish3693** [UniversalRobots/Universal_Robots_ROS_Driver#454]
While using a continuous stream of trajectory control message at 50Hz. The UR5e arm moves to the trajectory point with jittery motion.

**Comment by stefanscherzinger** [comment]
Hi @nitish3693 

> a continuous stream of trajectory control message at 50Hz

Could you be more specific on what you are doing?

- [ ] a: Using the [joint_trajectory_action interface](http://docs.ros.org/en/latest/api/control_msgs/html/action/FollowJointTrajectory.html) and sending action goals with `50Hz`
- [ ] b: Publishing a single action goal to the joint_trajectory_action interface and having the robot configured to run at `50Hz`. If so, how? The control frequency is only set [here](https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/master/src/rtde/rtde_client.cpp#L45) and [here](https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/master/src/rtde/rtde_client.cpp#L77) in the client library..
- [ ] c: Other
