### ISSUE TITLE
Unable to change host-ip for external control

### ISSUE THREAD

**Issue by SCh-J** [UniversalRobots/Universal_Robots_ROS_Driver#455]
# Summary
When trying to use the external control block I'm  unable to change the host-ip and the ports. 
They are always reset to their defaults when trying to launch the program on the CB3 controller.

# Versions

 - Affected Robot Software Version(s): Polyscape 3.7
 - Affected Robot Hardware Version(s): UR10 CB3
 - URCaps Software version(s): External Control 1.0.5

**Comment by fmauch** [comment]
Did you change them in the Installation and actually **save** your changed Installation?

**Comment by SCh-J** [comment]
Sorry, I was just confused that the IP didn't change immidiately.
