### ISSUE TITLE
Clock synchronization issue when running rviz

### ISSUE THREAD

**Issue by roy-augmentus** [UniversalRobots/Universal_Robots_ROS_Driver#469]
I keep running into rviz crashing after running it for a while to control the robot. The error message shows that there is some clock synchronization issue. Afterwards, I have to restart everything to get stuff to work again. Does anyone have any clue what is happening?
![Screenshot from 2021-09-20 16-55-07](https://user-images.githubusercontent.com/88221267/133978526-7f314a93-4c84-46a0-a57b-7eb43eda9f55.png)

**Comment by fmauch** [comment]
`Could not get fresh data package from robot` is a severe issue which can have multiple sources:
 - Lack of real-time support in your system -> Install an RT-Kernel (I guess you did, considering https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/436#issuecomment-922682957)
 - Too high system load on your system -> consider using a separate machine for controlling the robot.
 - Networking issues / too much traffic on the network connection -> consider using a dedicated direct connection between the robot and your machine.

Also see other issues such as #135, #187, #83, #56
