### ISSUE TITLE
move_test python dependencies description

### ISSUE THREAD

**Issue by urrsk** [UniversalRobots/Universal_Robots_ROS_Driver#484]
We should improve the [usage_example.md](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/usage_example.md#control-the-robot-using-the-test_move-script) with the information of how to install the dependencies for python3 for the [move_test](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/9bd11c497cc32a65e922c6dca3eb52dfa3ae6e4e/ur_robot_driver/scripts/test_move) script

It seem to work using:
```
sudo apt-get install python3-pip
pip3 install rospkg catkin_pkg
```

**Comment by fmauch** [comment]
Did he follow the build instructions? Those packages should be installed as dependencies when building the driver. And they should better not be installed via pip for compatibility reasons.

**Comment by fmauch** [comment]
Recreating the issue using a docker container brought me to the actual problem: The `test_move` script uses python3 while on ROS melodic the default python interpreter is python2. Therefore, the dependencies are not installed for python3. We'll have to fix that. My day was too long to figure out a complete solution today, but I can definitely confirm this.

One way of solving this would be to make the script python2 combatible and use a compatible shebang line.

Another one would be to use the python3 dependencies in the package.xml directly, given that they don't crash with the python2 versions installed.
