### ISSUE TITLE
How does ur10e obtain the information of the six-dimensional force sensor that comes with the end through ROS?

### ISSUE THREAD

**Issue by ksjz** [UniversalRobots/Universal_Robots_ROS_Driver#494]
I am using ur10e, and I want to obtain the information of the six-dimensional force sensor at the end of the robotic arm. Is there any example for reference, thank you.  
my pc is ：ubuntu 18.04+Melodic

**Comment by fmauch** [comment]
What do you mean by "obtain the information"? If you want to read the force-torque mesurements, they are published by default on the `wrench` topic.

```
rostopic echo /wrench
```

**Comment by ksjz** [comment]
> What do you mean by "obtain the information"? If you want to read the force-torque mesurements, they are published by default on the `wrench` topic.
> 
> ```
> rostopic echo /wrench
> ```

thank you! i got it
