### ISSUE TITLE
Access to the source package for the externalcontrol-1.0.5.urcap

### ISSUE THREAD

**Issue by nitish3693** [UniversalRobots/Universal_Robots_ROS_Driver#495]
# Summary

The URCap needs to be modified to update the keyboard for the HOST IP and Custom port, also to move the thread and function definitions currently located in the URCaps Program Script code to installation node. Would it be possible to share the source code for the URCap for externalcontrol-1.0.5.urcap to make the changes ? 

*Introduction to the issue*

# Versions
 - URCaps Software version(s): externalcontrol-1.0.5.urcap

**Comment by stefanscherzinger** [comment]
@nitish3693 [Here](https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap)'s the repository. Feel free to contribute with PRs and issues.
