### ISSUE TITLE
ROS Melodic:  urcl_log_handler.

### ISSUE THREAD

**Issue by tadeleTuli** [UniversalRobots/Universal_Robots_ROS_Driver#496]
Scanning dependencies of target sensor_msgs_generate_messages_nodejs
Universal_Robots_ROS_Driver/ur_robot_driver/CMakeFiles/urcl_log_handler.dir/build.make:62: recipe for target 'Universal_Robots_ROS_Driver/ur_robot_driver/CMakeFiles/urcl_log_handler.dir/src/urcl_log_handler.cpp.o' failed
make[2]: *** [Universal_Robots_ROS_Driver/ur_robot_driver/CMakeFiles/urcl_log_handler.dir/src/urcl_log_handler.cpp.o] Error 1
CMakeFiles/Makefile2:9399: recipe for target 'Universal_Robots_ROS_Driver/ur_robot_driver/CMakeFiles/urcl_log_handler.dir/all' failed
make[1]: *** [Universal_Robots_ROS_Driver/ur_robot_driver/CMakeFiles/urcl_log_handler.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Built target sensor_msgs_generate_messages_nodejs
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed

Any help of solving this problem is appreciated for ur3e.

**Comment by fmauch** [comment]
Some more context would probably be helpful:
 - What where the steps that you were executing? (Starting from the beginning, e.g. which packages did you clone into your workspace)
 - What is the **full** output you get from your build process?
 - Did you make sure that everything is up-to-date (`sudo apt update && sudo apt dist-upgrade` and `git pull` on all git repositories (where `git branch` in every repository should show which branches you are on))
