### ISSUE TITLE
Cannot connect to UR5e via ROS Noetic

### ISSUE THREAD

**Issue by yorgosk** [UniversalRobots/Universal_Robots_ROS_Driver#509]
# Summary

Your issue may already be reported!
Please search on the [issue track](../) before creating one.

*I cannot connect to UR5e through the `roslaunch ur_calibration calibration_correction.launch   robot_ip:=127.0.0.101 target_filename:="${HOME}/UR5/my_robot_calibration.yaml"` command, although I can successfully ping the same IP address.*

# Versions
 - ROS Driver version:
 - Affected Robot Software Version(s):
 - Affected Robot Hardware Version(s):
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s):
![ur5-calibration](https://user-images.githubusercontent.com/9288091/153907968-fb16fe5d-ae78-4e13-b7ea-a27fae5d6a05.png)
![ur5-ping](https://user-images.githubusercontent.com/9288091/153907971-0e0d2cea-5764-4d63-b56e-6062bf6fa538.png)

# Impact & Issue details
I cannot control the UR5 with my computer. So far, I have followed step-by-step the instructions as listed here https://github.com/UniversalRobots/Universal_Robots_ROS_Driver (binary package installation).
I have also manually set-up the robot IP address and subnet mask, following whatever relevant instructions I could find online as well as in the relevant issues.
I think I may be missing something really basic, because it really is a fresh robot and a fresh installation of everything, but this issue has already been bothering me for many hours.

**Comment by gavanderhoorn** [comment]
`127.0.0.101` would fall in the [loopback range](https://en.wikipedia.org/wiki/Localhost), which is a range of IP addresses which always points to *the local computer* (or: the local network card on which the TCP/IP stack is configured).

You cannot use it to communicate with another host, not even if that host is on the same network and has configured `127.0.0.101` as its IP.

> I can successfully ping the same IP address.

that would make sense, as you're essentially pinging yourself.

For ICMP echo that's OK.

But the driver will really want to 'talk' to a UR controller, and it can't, as it's trying to connect to your own PC, which will not be listening on the correct TCP ports.

> I have also manually set-up the robot IP address and subnet mask, following whatever relevant instructions I could find online as well as in the relevant issues.

you should pick a different IP address.

If you have no existing network infrastructure, something from the `10.x.y.z` range could work, or `192.168.x.y`.
