### ISSUE TITLE
I want to make an UR3e moving while receiving TCP force/torque value with ROS.

### ISSUE THREAD

**Issue by osumilab** [UniversalRobots/Universal_Robots_ROS_Driver#522]
# Summary

I want to make an UR3e moving while receiving  force/torque value with ROS.

*Introduction to the issue*

# Versions
 - ROS Driver version:ROS Noetic with Ubuntu 20.04
 - Affected Robot Software Version(s):UR3e
 - Affected Robot Hardware Version(s):
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s):

# Issue details
Hello,dear all.

I want to make an UR3e moving while receiving  force/torque value with ROS.
I want to use force_torque_sensor_controller, and its topic /wrench to achieve this goal but are not sure how to use it.

`rostopic echo /wrench`

I can check the force and torque values with the above commands, but when I display them in rqt_plot, I do not see the details of the topics after /wrench as shown in the picture.
![Screenshot from 2022-04-24 17-31-31](https://user-images.githubusercontent.com/84759514/164967485-e6fde62e-6285-4838-b11e-ea95d0e721f3.png)

In addition, we would like to control the UR3e according to the force values acquired in the future, and we would appreciate a little information on how to do this (mainly programming in python).
At the moment, Moveit is successfully used to run UR3e.
In the future, we are considering stopping the robot movement if a certain force value is exceeded.

It is my lack of understanding of ROS and Topic, but I would like help.

**Comment by fmauch** [comment]
Such questions are better asked on ROS answers as this is not really an issue with the driver, but general ROS usage.

in rqt_plot you'll have to access message values directly using e.g. `/wrench/wrench/force/x`. Do the same for all the other axes in case you're interested in them.

You could write a small node that listens to that topic and then aborts any motions from the controller using the action_server's `cancel` topic. However, be aware that this will not be reacting really fast (in terms of only a couple of milliseconds) but might take around 100-500ms (or even longer in edge cases) as ROS topic communication is not deterministically fast. A more direct approach would be to use a force controller directly, such as [cartesian_controllers](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers) (Disclaimer: my team is the author of that), but this will not be usable with MoveIt.
