### ISSUE TITLE
How to **programatically** check driver has launched successfully?

### ISSUE THREAD

**Issue by bryangd34** [UniversalRobots/Universal_Robots_ROS_Driver#527]
This is more of a question than a issue report. I apologise in advance if this is not the appropriate place to ask.

After I run `roslaunch ur_robot_driver <robot_type>_bringup.launch` , I then visually check the output for the message "Robot ready to receive commands" and that there are no error messages. At this point, I know that the driver launched successfully and I can start controlling the robot.

But what if I am using another control program, and want to check that the driver has successfully launched using this control program. Is there something I can check to confirm success (like a topic, for example)? 

Thank you.

**Comment by akdhandy** [comment]
Hello,

When you launch the ```ur_robot_driver``` for your respective UR arm,echo the corresponding topic :
 ```rostopic echo /arm/ur_hardware_interface/robot_mode``` which lists out the current Robot state.

**Comment by bryangd34** [comment]
Thanks! That is what I am looking for.
