### ISSUE TITLE
Robotiq 2F with UR5 CB3 robot

### ISSUE THREAD

**Issue by twtoner** [UniversalRobots/Universal_Robots_ROS_Driver#548]
# Summary

I have a UR5 (CB3, not e-series) with a Robotiq 2F-85 gripper and Robotiq FT300 force/torque sensor connected to internal USB ports inside the cabinet. I can successfully move the UR5 using MoveIt through the ROS driver, but I do not understand how the gripper and FT sensor are meant to be controlled or read from with a CB3 using the ROS driver. I see that e-series robots have special tool-oriented arguments in their .launch files, but it appears those are missing from CB3 robots. Likewise, almost all questions on here are related to e-series.

All I really need to do is position the UR5 at specific Cartesian poses and open/close the gripper using predefined position/speed/force, though FT feedback and programmatic gripping would be nice if possible. What is the simplest and best-supported way to do this? I can interface with the devices with scripts written on the pendant, so I know those work, but I would also like to use the ROS driver if possible. 

Any help would be greatly appreciated!

# Versions
 - ROS Driver version: Ubuntu 20.04, ROS Noetic
 - Affected Robot Software Version(s): 3.15.7.1.106331
 - Affected Robot Hardware Version(s): UR5 
 - Robot Serial Number: 
 - UR+ product(s) installed: 
 - URCaps Software version(s): Robotiq Gripper UCG-1.8.10.17249; Robotiq Copilot 1.24.1.16541; External Control 

# Current approach
Since my original post, I have discovered that it is possible to achieve discrete gripper open/close by setting a digital IO pin between 0 and 1 using, for example:

`rosservice call /ur_hardware_interface/set_io "fun: 1 pin: 0 state: 1`

which sets the digital output pin 0 to 1 (true). The meaning of each argument was not immediately obvious to me, but I found that the definition of `ur_msgs/SetIO` helps: [here](http://docs.ros.org/en/kinetic/api/ur_msgs/html/srv/SetIO.html). 

Is this a recommended approach?

**Comment by fmauch** [comment]
>Since my original post, I have discovered that it is possible to achieve discrete gripper open/close by setting a digital IO pin between 0 and 1 using, for example:
>
>rosservice call /ur_hardware_interface/set_io "fun: 1 pin: 0 state: 1
>
>which sets the digital output pin 0 to 1 (true). The meaning of each argument was not immediately obvious to me, but I found that the definition of ur_msgs/SetIO helps: [here](http://docs.ros.org/en/kinetic/api/ur_msgs/html/srv/SetIO.html).
>
>Is this a recommended approach?

That would indeed be the workaround I would have proposed.
