### ISSUE TITLE
UR20 Support

### ISSUE THREAD

**Issue by christinaionescu** [UniversalRobots/Universal_Robots_ROS_Driver#559]
Hi,

I hope this is the correct forum for this question:
When do you plan to release support for UR20, also regarding moveit (https://github.com/fmauch/universal_robot/tree/calibration_devel )?

Thank you!
Best regards

**Comment by fmauch** [comment]
I've created an issue in the description repo: https://github.com/ros-industrial/universal_robot/issues/605
