### ISSUE TITLE
Using freedrive mode triggers error on teach pendant: freedrive_mode(): Arguments 'a' and 'V' must be positive

### ISSUE THREAD

**Issue by faev999** [UniversalRobots/Universal_Robots_ROS_Driver#583]
# Summary

The issue I am experiencing is not yet listed on the existing issues

*Introduction to the issue*

# Versions
 - ROS Driver version:
 - Affected Robot Software Version(s): 5.12.0-2
 - Affected Robot Hardware Version(s): UR10e
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s):

# Impact
not being able to switch to freedrive mode

# Issue details
when using the freedrive service implementation suggested here [freedrive service](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/546#issuecomment-1156807786) there's an error in the teach-pendandt that reads `freedrive_mode(): Arguments 'a' and 'V' must be positive`. as described before this only happens on polyscope 5.12, it works perfectly fine on 5.11. 

I found this [bit](https://forum.universal-robots.com/t/freedrive-mode-argument-a-and-v-must-be-positive/23443) on the official Ur forum: apparently it's a bug on the 5.12.x versions less than 5.12.4(bug fixed). I recon it's important to put this info here because it's my understanding (maybe I am wrong) that they are changing the way freedrive should be used, and it might be important for [#546](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/546) and [#573](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/573)

## Project status at point of discovered
*When did you first observe the issue?*
when testing on a robot with polyscope 5.12.0

## Steps to Reproduce
launch driver and trying to call freedrive service

## Expected Behavior
robot entering freedrive mode 

## Actual Behavior
error on teach pendant screen

## Workaround Suggestion
for now downgrade to 5.11 or upgrade to 5.12.4

**Comment by fmauch** [comment]
Since this has never been responded to, this should not get closed before further investigation is done.
