### ISSUE TITLE
/ur_hardware_interface/script_command std_msgs

### ISSUE THREAD

**Issue by sunnymints** [UniversalRobots/Universal_Robots_ROS_Driver#587]
# Summary
Although I found many similar questions, I could not find a complete solution. I want to ues "/ur_hardware_interface/script_command std_msgs'' topic send UR_script command such as seedj and movej.
I try to use two method:
First:
rostopic pub /ur_hardware_interface/script_command std_msgs/String "data: 'movel([0.5,0.5,0.5,3.14,-1.57,1.57])'"

Second:

#!/usr/bin/env python

import rospy
from std_msgs.msg import String

rospy.init_node('vel_script_node')
pub=rospy.Publisher('/ur_hardware_interface/script_command', String, queue_size=10)
rate=rospy.Rate(10)
vel_script="speedj([0,0,0,0,0,-1.0],0.5,0.5)"

while not rospy.is_shutdown():
pub.publish(vel_script)
rate.sleep()

but it no any response. Beside, I can not find remote-control mode on our ur5 URCap (I think it alreadly open in ur5).

# Versions
 - ROS Driver version: melodic
 - Affected Robot Software Version(s): URCap V-3.9.1
 - Affected Robot Hardware Version(s): UR5
 - Robot Serial Number: UR5
 - UR+ product(s) installed:
 - URCaps Software version(s):V-3.9.1

Thanks

**Comment by RobertWilbrandt** [comment]
Sorry for the late answer. I just tried replicating this problem in ursim:
```console
docker network create --subnet=192.168.56.0/24 ursim_net
docker run --rm -d --net ursim_net --ip 192.168.56.101 -e ROBOT_MODEL=ur5 --name ursim universalrobots/ursim_cb3
```

and then 

```console
roslaunch ur_robot_driver ur5_bringup.launch robot_ip:=192.168.56.101 headless_mode:=true
```

Both of your commands actually poduced motion for me:
```console
rostopic pub /ur_hardware_interface/script_command std_msgs/String "data: 'movel([0.5,0.5,0.5,3.14,-1.57,1.57])'"
rostopic pub /ur_hardware_interface/script_command std_msgs/String "data: 'speedj([0,0,0,0,0,-1.0],0.5,0.5)'" -r 10
```

For your first problem: Are you aware of the pose notation used in URScript? The rotation is defined in axis-angle notation (see the URScript programming manual) and this seems like you wanted to specify it using euler angles.

Generally, can you show the output of the ur driver? An error like `Sending data through socket failed.` could help us narrow down the problem.

The remote-control mode is not relevant to your setup, as it is only available in e-series robots.
