### ISSUE TITLE
Connection refused with UR5e and ROS noetic

### ISSUE THREAD

**Issue by stevensu1838** [UniversalRobots/Universal_Robots_ROS_Driver#590]
The IP of Ubuntu machine is 192.168.0.180
![image](https://user-images.githubusercontent.com/25648734/203770333-0c390a71-2fca-48ec-9af3-0dfd446d86fb.png)

Set up the IP of UR5e robot, I first got this IP by click DHCP and then made this same IP 192.168.0.177 as Static 

![image](https://user-images.githubusercontent.com/25648734/203772072-5c6831ac-0ee1-4e73-9ccd-d634bdcb5e62.png)

![image](https://user-images.githubusercontent.com/25648734/203772286-10e45549-2dca-4cce-b6b5-eb61a8e6ecad.png)
![image](https://user-images.githubusercontent.com/25648734/203772351-cb5d3a19-394f-46e5-a18d-87bccecce7e9.png)

I can ping the UR5e robot (192.168.0.177) from Ubuntu PC (192.168.0.180) with no problem, however, when I click play, It throws the error below on the teach pendant: 
![image](https://user-images.githubusercontent.com/25648734/203772436-4ce2eda0-906d-48d2-89ae-8baed098ea8d.png)

And in Rviz no UR5e robot shows up. Could you please help? 

# Versions
 - ROS Driver version: 
 - Affected Robot Software Version(s): URSoftware 5.12.2.1101534
 - Affected Robot Hardware Version(s):
 - Robot Serial Number: 20225501705
 - UR+ product(s) installed:
 - URCaps Software version(s): v1.0.5](https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap/releases/tag/v1.0.5)

**Comment by fmauch** [comment]
Did you run the ros driver on the ROS machine before pressing play as [written in the README](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#quick-start)?

**Comment by fmauch** [comment]
Or maybe a more stupid question: Did you start the ROS driver beforehand?
