### ISSUE TITLE
Error while Setting up Ubuntu with a PREEMPT_RT kernel

### ISSUE THREAD

**Issue by stevensu1838** [UniversalRobots/Universal_Robots_ROS_Driver#591]
### ysu66@mech1936:~/rt_kernel_build/linux-5.15.79$ make -j `getconf _NPROCESSORS_ONLN` deb-pkg
  UPD     include/config/kernel.release
make clean
sh ./scripts/package/mkdebian
  TAR     linux-upstream.tar.gz
origversion=$(dpkg-parsechangelog -SVersion |sed 's/-[^-]*$//');\
	mv linux-upstream.tar.gz ../linux-upstream_${origversion}.orig.tar.gz
dpkg-buildpackage -r"fakeroot -u" -a$(cat debian/arch)  -i.git -us -uc
dpkg-buildpackage: info: source package linux-upstream
dpkg-buildpackage: info: source version 5.15.79-rt54-1
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by ysu66 <ysu66@mech1936>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source -i.git --before-build .
 debian/rules clean
rm -rf debian/*tmp debian/files
make clean
 dpkg-source -i.git -b .
dpkg-source: info: using source format '1.0'
dpkg-source: warning: source directory 'linux-5.15.79' is not <sourcepackage>-<upstreamversion> 'linux-upstream-5.15.79-rt54'
dpkg-source: warning: .orig directory name linux-5.15.79.orig is not <package>-<upstreamversion> (wanted linux-upstream-5.15.79-rt54.orig)
dpkg-source: info: building linux-upstream using existing linux-upstream_5.15.79-rt54.orig.tar.gz
dpkg-source: info: building linux-upstream in linux-upstream_5.15.79-rt54-1.diff.gz
dpkg-source: warning: ignoring deletion of file .scmversion
dpkg-source: warning: the diff modifies the following upstream files: 
 .clang-format
 .cocciconfig
 .get_maintainer.ignore
 .mailmap
 CREDITS
 MAINTAINERS
 README
dpkg-source: info: use the '3.0 (quilt)' format to have separate and documented changes to upstream files, see dpkg-source(1)
dpkg-source: info: building linux-upstream in linux-upstream_5.15.79-rt54-1.dsc
dpkg-source: warning: missing information for output field Standards-Version
 debian/rules binary
make KERNELRELEASE=5.15.79-rt54 ARCH=x86 	KBUILD_BUILD_VERSION=1 -f ./Makefile
  WRAP    arch/x86/include/generated/uapi/asm/bpf_perf_event.h
  WRAP    arch/x86/include/generated/uapi/asm/fcntl.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctl.h
  WRAP    arch/x86/include/generated/uapi/asm/errno.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctls.h
  WRAP    arch/x86/include/generated/uapi/asm/ipcbuf.h
  WRAP    arch/x86/include/generated/uapi/asm/param.h
  WRAP    arch/x86/include/generated/uapi/asm/resource.h
  WRAP    arch/x86/include/generated/uapi/asm/socket.h
  WRAP    arch/x86/include/generated/uapi/asm/sockios.h
  WRAP    arch/x86/include/generated/uapi/asm/termbits.h
  UPD     include/generated/uapi/linux/version.h
  WRAP    arch/x86/include/generated/uapi/asm/termios.h
  WRAP    arch/x86/include/generated/uapi/asm/poll.h
  WRAP    arch/x86/include/generated/uapi/asm/types.h
  HOSTCC  scripts/basic/fixdep
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_64.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_x32.h
  HYPERCALLS arch/x86/include/generated/asm/xen-hypercalls.h
  DESCEND objtool
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/export.h
  WRAP    arch/x86/include/generated/asm/irq_regs.h
  DESCEND bpf/resolve_btfids
  UPD     include/generated/utsrelease.h
  WRAP    arch/x86/include/generated/asm/local64.h
  WRAP    arch/x86/include/generated/asm/kmap_size.h
  WRAP    arch/x86/include/generated/asm/mmiowb.h
  WRAP    arch/x86/include/generated/asm/module.lds.h
  WRAP    arch/x86/include/generated/asm/rwonce.h
  WRAP    arch/x86/include/generated/asm/unaligned.h
<stdin>:1:10: fatal error: libelf.h: No such file or directory
compilation terminated.
  MKDIR     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//libbpf
  MKDIR     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//libsubcmd
  HOSTCC  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/fixdep.o
  HOSTCC  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/fixdep.o
  GEN     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/bpf_helper_defs.h
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/fixdep-in.o
  LINK    /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/fixdep
  MKDIR   /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/
  MKDIR   /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/
  MKDIR   /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/
  HOSTLD  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/fixdep-in.o
  MKDIR   /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/nlattr.o
  LINK    /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/fixdep
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/bpf.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/btf.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf_errno.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/str_error.o
  HOSTCC  scripts/genksyms/genksyms.o
btf.c:18:10: fatal error: gelf.h: No such file or directory
   18 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[7]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/btf.o] Error 1
make[7]: *** Waiting for unfinished jobs....
  YACC    scripts/genksyms/parse.tab.[ch]
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/exec-cmd.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/main.o
libbpf.c:47:10: fatal error: libelf.h: No such file or directory
   47 | #include <libelf.h>
      |          ^~~~~~~~~~
compilation terminated.
make[7]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:96: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf.o] Error 1
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/rbtree.o
  HOSTCC  scripts/selinux/genheaders/genheaders
main.c:55:10: fatal error: libelf.h: No such file or directory
   55 | #include <libelf.h>
      |          ^~~~~~~~~~
compilation terminated.
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/main.o] Error 1
make[6]: *** Waiting for unfinished jobs....
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/exec-cmd.o
  HOSTCC  scripts/bin2c
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/selinux/mdp/mdp
  LEX     scripts/genksyms/lex.lex.c
make[5]: *** [Makefile:62: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//resolve_btfids-in.o] Error 2
make[5]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/sorttable
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/help.o
  HOSTCC  scripts/asn1_compiler
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/pager.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTLD  arch/x86/tools/relocs
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/help.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/pager.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/parse-options.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/special.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/weak.o
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/arch.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/check.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/special.h:10,
                 from arch/x86/special.c:4:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[7]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/special.o] Error 1
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:139: arch/x86] Error 2
make[6]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/sign-file
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/parse-options.o
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from weak.c:10:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/weak.o] Error 1
make[5]: *** [Makefile:56: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/objtool-in.o] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/run-command.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/sigchain.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/run-command.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/subcmd-config.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/sigchain.o
  HOSTCC  scripts/extract-cert
  HOSTCC  scripts/insert-sys-cert
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/subcmd-config.o
make[6]: *** [Makefile:158: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf-in.o] Error 2
make[5]: *** [Makefile:48: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//libbpf/libbpf.a] Error 2
  HOSTLD  scripts/genksyms/genksyms
  LD      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/libsubcmd-in.o
  AR      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/libsubcmd.a
make[4]: *** [Makefile:72: bpf/resolve_btfids] Error 2
make[3]: *** [Makefile:1403: tools/bpf/resolve_btfids] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/devicetable-offsets.s
  UPD     scripts/mod/devicetable-offsets.h
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/sumversion.o
  LD      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/libsubcmd-in.o
  AR      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/libsubcmd.a
make[4]: *** [Makefile:69: objtool] Error 2
make[3]: *** [Makefile:1403: tools/objtool] Error 2
  HOSTLD  scripts/mod/modpost
  CC      kernel/bounds.s
  CALL    scripts/atomic/check-atomics.sh
  UPD     include/generated/timeconst.h
  UPD     include/generated/bounds.h
  CC      arch/x86/kernel/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1608: deb-pkg] Error 2
ysu66@mech1936:~/rt_kernel_build/linux-5.15.79$ make -j `getconf _NPROCESSORS_ONLN` deb-pkg^C
ysu66@mech1936:~/rt_kernel_build/linux-5.15.79$ make -j `getconf _NPROCESSORS_ONLN` deb-pkg
make clean
  CLEAN   arch/x86/tools
sh ./scripts/package/mkdebian
  TAR     linux-upstream.tar.gz
origversion=$(dpkg-parsechangelog -SVersion |sed 's/-[^-]*$//');\
	mv linux-upstream.tar.gz ../linux-upstream_${origversion}.orig.tar.gz
dpkg-buildpackage -r"fakeroot -u" -a$(cat debian/arch)  -i.git -us -uc
dpkg-buildpackage: info: source package linux-upstream
dpkg-buildpackage: info: source version 5.15.79-rt54-1
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by ysu66 <ysu66@mech1936>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source -i.git --before-build .
 debian/rules clean
rm -rf debian/*tmp debian/files
make clean
 dpkg-source -i.git -b .
dpkg-source: info: using source format '1.0'
dpkg-source: warning: source directory 'linux-5.15.79' is not <sourcepackage>-<upstreamversion> 'linux-upstream-5.15.79-rt54'
dpkg-source: warning: .orig directory name linux-5.15.79.orig is not <package>-<upstreamversion> (wanted linux-upstream-5.15.79-rt54.orig)
dpkg-source: info: building linux-upstream using existing linux-upstream_5.15.79-rt54.orig.tar.gz
dpkg-source: info: building linux-upstream in linux-upstream_5.15.79-rt54-1.diff.gz
dpkg-source: warning: ignoring deletion of file .scmversion
dpkg-source: warning: the diff modifies the following upstream files: 
 .clang-format
 .cocciconfig
 .get_maintainer.ignore
 .mailmap
 CREDITS
 MAINTAINERS
 README
dpkg-source: info: use the '3.0 (quilt)' format to have separate and documented changes to upstream files, see dpkg-source(1)
dpkg-source: info: building linux-upstream in linux-upstream_5.15.79-rt54-1.dsc
dpkg-source: warning: missing information for output field Standards-Version
 debian/rules binary
make KERNELRELEASE=5.15.79-rt54 ARCH=x86 	KBUILD_BUILD_VERSION=1 -f ./Makefile
  HOSTCC  scripts/basic/fixdep
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_64.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_x32.h
  HYPERCALLS arch/x86/include/generated/asm/xen-hypercalls.h
  DESCEND objtool
  DESCEND bpf/resolve_btfids
  MKDIR     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//libbpf
  MKDIR     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//libsubcmd
<stdin>:1:10: fatal error: libelf.h: No such file or directory
compilation terminated.
  HOSTCC  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/fixdep.o
  HOSTCC  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/fixdep.o
  GEN     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/bpf_helper_defs.h
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/fixdep-in.o
  LINK    /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/fixdep
  HOSTCC  scripts/bin2c
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/sorttable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/genksyms/genksyms.o
  HOSTLD  /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/fixdep-in.o
  MKDIR   /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/
  LINK    /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/fixdep
  HOSTCC  scripts/selinux/genheaders/genheaders
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf.o
  HOSTCC  scripts/selinux/mdp/mdp
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/exec-cmd.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/help.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/exec-cmd.o
libbpf.c:47:10: fatal error: libelf.h: No such file or directory
   47 | #include <libelf.h>
      |          ^~~~~~~~~~
compilation terminated.
make[7]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf.o] Error 1
make[6]: *** [Makefile:158: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libbpf/staticobjs/libbpf-in.o] Error 2
make[5]: *** [Makefile:48: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids//libbpf/libbpf.a] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/help.o
  YACC    scripts/genksyms/parse.tab.[ch]
  LEX     scripts/genksyms/lex.lex.c
  HOSTCC  scripts/sign-file
  HOSTLD  arch/x86/tools/relocs
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/pager.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/pager.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/parse-options.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/run-command.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/sigchain.o
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/extract-cert
  HOSTCC  scripts/insert-sys-cert
  HOSTCC  scripts/genksyms/lex.lex.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/parse-options.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/subcmd-config.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/run-command.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/sigchain.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/subcmd-config.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/weak.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/check.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/special.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/special.o
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/orc_gen.o
  MKDIR   /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/lib/
  GEN     /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/lib/inat-tables.c
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from weak.c:10:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/weak.o] Error 1
make[6]: *** Waiting for unfinished jobs....
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/arch.h:11,
                 from check.c:14:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/check.o] Error 1
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/arch.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/check.h:11,
                 from orc_gen.c:12:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/orc_gen.o] Error 1
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/arch.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/check.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/special.h:10,
                 from arch/x86/special.c:4:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
  CC      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/decode.o
make[7]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/special.o] Error 1
make[7]: *** Waiting for unfinished jobs....
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/arch.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/check.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/special.h:10,
                 from special.c:16:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/special.o] Error 1
In file included from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/objtool.h:13,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/arch.h:11,
                 from /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/check.h:11,
                 from arch/x86/decode.c:18:
/home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[7]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:97: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/arch/x86/decode.o] Error 1
make[6]: *** [/home/ysu66/rt_kernel_build/linux-5.15.79/tools/build/Makefile.build:139: arch/x86] Error 2
make[5]: *** [Makefile:56: /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/objtool-in.o] Error 2
make[5]: *** Waiting for unfinished jobs....
  LD      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/libsubcmd-in.o
  AR      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/objtool/libsubcmd.a
make[4]: *** [Makefile:69: objtool] Error 2
make[3]: *** [Makefile:1403: tools/objtool] Error 2
make[3]: *** Waiting for unfinished jobs....
  LD      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/libsubcmd-in.o
  HOSTLD  scripts/genksyms/genksyms
  AR      /home/ysu66/rt_kernel_build/linux-5.15.79/tools/bpf/resolve_btfids/libsubcmd/libsubcmd.a
make[4]: *** [Makefile:72: bpf/resolve_btfids] Error 2
make[3]: *** [Makefile:1403: tools/bpf/resolve_btfids] Error 2
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1608: deb-pkg] Error 2

**Comment by stevensu1838** [comment]
![image](https://user-images.githubusercontent.com/25648734/204083391-63f6ed71-d6be-47f7-af51-e77d6e9e267e.png)

**Comment by stevensu1838** [comment]
![image](https://user-images.githubusercontent.com/25648734/204083571-b12c17a7-cb2a-4105-8ab3-ec26f3a8d50e.png)

**Comment by RobertWilbrandt** [comment]
We cannot help you if you provide nothing more than a console log. Did you follow the [Real-Time setup guide](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/real_time.md)?

In any way: Provide us with a complete list of command that lead to this error.

**Comment by stevensu1838** [comment]
Hi all,
I've provided more details [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/618#issue-1595993795). Could you please help?
