### ISSUE TITLE
dashboard client receive timeout reset to 1 s

### ISSUE THREAD

**Issue by steffen-roperobotics** [UniversalRobots/Universal_Robots_ROS_Driver#597]
# Summary

The dash board client receive timeout is reset to 1 s when the client connects and the receive timeout specified by the parameter is ignored. 

*Introduction to the issue*

# Versions
 - ROS Driver version: noetic
 - Affected Robot Software Version(s): URSoftware 3.15.8.106339
 - Affected Robot Hardware Version(s):  CB3.1
 - Robot Serial Number: 2019300369
 - UR+ product(s) installed: None
 - URCaps Software version(s): None

# Impact
When loading a new installation file the dashboard client timesout and shutdown.  The client does not reconnect. 

# Issue details
*This part is important in order to clarify the severity of the issue.*

## Use Case and Setup
*What does the setup look like and what are the objectives?*

## Project status at point of discovered
I just recently updated our robot ros version from kinetic to noetic and at the same time I updated the universal_robot_ros_driver to the latest commit on the master branch.  After I had updated to the lastest commit on the master branch the dashboard client would timeout when loading a different installation file. I noticed that the receive timeout was reset in the dashboard client connect funciton.

## Steps to Reproduce
To reproduce the error set the receive timeout to 10 s on the parameter server and connect the dashboard client. When the client is connected use the ur_hardware_interface/dashboard/load_installation service to load an installation file - the client should timeout and shutdown. 

## Expected Behavior
The client should not timeout when loading a different installation file and shutdown.

## Actual Behavior
The client did timeout when loading a different installation file and then it shutdown.

## Workaround Suggestion
I have solved the issue by moving the call setReceiveTimeout in the function DashboardClientROS::connect function to after the client::connect in order to avoid that the receive timeout is reset in the client::connect function - take a look at the pull request #596 for my solution.

**Comment by fmauch** [comment]
still to test
