### ISSUE TITLE
Error 'Could not correctly initialize robot. Exiting'

### ISSUE THREAD

**Issue by 7519060** [UniversalRobots/Universal_Robots_ROS_Driver#599]
# Summary
I cannot connect UR3 to my PC with ur_robot_driver. 
When I run 
`
roslaunch ur_robot_driver ur3_bringup.launch robot_ip:=192.168.56.1 kinematics_config:=$(rospack find ur_robot_driver)/config/ur3_calibration.yaml 
`
, I got 
"Variable 'tcp_offset' not recognized by the robot. Probably your output recipe contains errors" and "Could not correctly initialize robot. Exiting".

# Versions
 - ROS Driver version:ubuntu 18.04 + melodic
 - Affected Robot Software Version(s):3.8.0.61336
 - Affected Robot Hardware Version(s):UR3
 - Robot Serial Number:2016331423
 - URCaps Software version(s):externalcontrol-1.0.5.urcap 

# Impact
I cannot use ur_robot_driver becaues of the error. Error messages says 

> [FATAL] [1671551631.516733597]: Variable 'tcp_offset' not recognized by the robot. Probably your output recipe contains errors

> [ERROR] [1671551631.516866722]: Could not correctly initialize robot. Exiting

I'm new to ROS. If something is wrong with this post, please tell me.
I would appreciate it if you could give me a solution.

# Issue details
In order to use "velocity_controllers/JointGroupVelocityController" type as a topic, I needed to upgrade my driver for universal robot ur3. I followed steps written in README except realtime kernel setups(I couldn't locate the right key using "gpg2 " ). 
From terminal, when I run the command 
`roslaunch ur_robot_driver ur3_bringup.launch robot_ip:=192.168.56.1 kinematics_config:=$(rospack find ur_robot_driver)/config/ur3_calibration.yaml 
`
, I got 

> 
> sgn@ren:~/vs_ws$ roslaunch ur_robot_driver ur3_bringup.launch robot_ip:=192.168.56.1 kinematics_config:=$(rospack find ur_robot_driver)/config/ur3_calibration.yaml [script_sender_port:=SCRIPT_SENDER_PORT]
> ... logging to /home/sgn/.ros/log/7b359b70-807e-11ed-87f9-f02f74a14b89/roslaunch-ren-7989.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://ren:42793/
> 
> 
> SUMMARY
> 
> PARAMETERS
>  * /controller_stopper/consistent_controllers: ['joint_state_con...
>  * /force_torque_sensor_controller/publish_rate: 125
>  * /force_torque_sensor_controller/type: force_torque_sens...
>  * /forward_cartesian_traj_controller/joints: ['shoulder_pan_jo...
>  * /forward_cartesian_traj_controller/type: pass_through_cont...
>  * /forward_joint_traj_controller/joints: ['shoulder_pan_jo...
>  * /forward_joint_traj_controller/type: pass_through_cont...
>  * /hardware_control_loop/loop_hz: 125
>  * /joint_based_cartesian_traj_controller/base: base
>  * /joint_based_cartesian_traj_controller/joints: ['shoulder_pan_jo...
>  * /joint_based_cartesian_traj_controller/tip: tool0
>  * /joint_based_cartesian_traj_controller/type: position_controll...
>  * /joint_group_vel_controller/joints: ['shoulder_pan_jo...
>  * /joint_group_vel_controller/type: velocity_controll...
>  * /joint_state_controller/publish_rate: 125
>  * /joint_state_controller/type: joint_state_contr...
>  * /pos_joint_traj_controller/action_monitor_rate: 20
>  * /pos_joint_traj_controller/constraints/elbow_joint/goal: 0.1
>  * /pos_joint_traj_controller/constraints/elbow_joint/trajectory: 0.2
>  * /pos_joint_traj_controller/constraints/goal_time: 0.6
>  * /pos_joint_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
>  * /pos_joint_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
>  * /pos_joint_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
>  * /pos_joint_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
>  * /pos_joint_traj_controller/constraints/stopped_velocity_tolerance: 0.05
>  * /pos_joint_traj_controller/constraints/wrist_1_joint/goal: 0.1
>  * /pos_joint_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
>  * /pos_joint_traj_controller/constraints/wrist_2_joint/goal: 0.1
>  * /pos_joint_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
>  * /pos_joint_traj_controller/constraints/wrist_3_joint/goal: 0.1
>  * /pos_joint_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
>  * /pos_joint_traj_controller/joints: ['shoulder_pan_jo...
>  * /pos_joint_traj_controller/state_publish_rate: 125
>  * /pos_joint_traj_controller/stop_trajectory_duration: 0.5
>  * /pos_joint_traj_controller/type: position_controll...
>  * /pose_based_cartesian_traj_controller/base: base
>  * /pose_based_cartesian_traj_controller/joints: ['shoulder_pan_jo...
>  * /pose_based_cartesian_traj_controller/tip: tool0_controller
>  * /pose_based_cartesian_traj_controller/type: pose_controllers/...
>  * /robot_description: <?xml version="1....
>  * /robot_status_controller/handle_name: industrial_robot_...
>  * /robot_status_controller/publish_rate: 10
>  * /robot_status_controller/type: industrial_robot_...
>  * /rosdistro: melodic
>  * /rosversion: 1.14.13
>  * /scaled_pos_joint_traj_controller/action_monitor_rate: 20
>  * /scaled_pos_joint_traj_controller/constraints/elbow_joint/goal: 0.1
>  * /scaled_pos_joint_traj_controller/constraints/elbow_joint/trajectory: 0.2
>  * /scaled_pos_joint_traj_controller/constraints/goal_time: 0.6
>  * /scaled_pos_joint_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
>  * /scaled_pos_joint_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
>  * /scaled_pos_joint_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
>  * /scaled_pos_joint_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
>  * /scaled_pos_joint_traj_controller/constraints/stopped_velocity_tolerance: 0.05
>  * /scaled_pos_joint_traj_controller/constraints/wrist_1_joint/goal: 0.1
>  * /scaled_pos_joint_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
>  * /scaled_pos_joint_traj_controller/constraints/wrist_2_joint/goal: 0.1
>  * /scaled_pos_joint_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
>  * /scaled_pos_joint_traj_controller/constraints/wrist_3_joint/goal: 0.1
>  * /scaled_pos_joint_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
>  * /scaled_pos_joint_traj_controller/joints: ['shoulder_pan_jo...
>  * /scaled_pos_joint_traj_controller/state_publish_rate: 125
>  * /scaled_pos_joint_traj_controller/stop_trajectory_duration: 0.5
>  * /scaled_pos_joint_traj_controller/type: position_controll...
>  * /scaled_vel_joint_traj_controller/action_monitor_rate: 20
>  * /scaled_vel_joint_traj_controller/constraints/elbow_joint/goal: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/elbow_joint/trajectory: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/goal_time: 0.6
>  * /scaled_vel_joint_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/stopped_velocity_tolerance: 0.05
>  * /scaled_vel_joint_traj_controller/constraints/wrist_1_joint/goal: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/wrist_2_joint/goal: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/wrist_3_joint/goal: 0.1
>  * /scaled_vel_joint_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
>  * /scaled_vel_joint_traj_controller/gains/elbow_joint/d: 0.1
>  * /scaled_vel_joint_traj_controller/gains/elbow_joint/i: 0.05
>  * /scaled_vel_joint_traj_controller/gains/elbow_joint/i_clamp: 1
>  * /scaled_vel_joint_traj_controller/gains/elbow_joint/p: 5.0
>  * /scaled_vel_joint_traj_controller/gains/shoulder_lift_joint/d: 0.1
>  * /scaled_vel_joint_traj_controller/gains/shoulder_lift_joint/i: 0.05
>  * /scaled_vel_joint_traj_controller/gains/shoulder_lift_joint/i_clamp: 1
>  * /scaled_vel_joint_traj_controller/gains/shoulder_lift_joint/p: 5.0
>  * /scaled_vel_joint_traj_controller/gains/shoulder_pan_joint/d: 0.1
>  * /scaled_vel_joint_traj_controller/gains/shoulder_pan_joint/i: 0.05
>  * /scaled_vel_joint_traj_controller/gains/shoulder_pan_joint/i_clamp: 1
>  * /scaled_vel_joint_traj_controller/gains/shoulder_pan_joint/p: 5.0
>  * /scaled_vel_joint_traj_controller/gains/wrist_1_joint/d: 0.1
>  * /scaled_vel_joint_traj_controller/gains/wrist_1_joint/i: 0.05
>  * /scaled_vel_joint_traj_controller/gains/wrist_1_joint/i_clamp: 1
>  * /scaled_vel_joint_traj_controller/gains/wrist_1_joint/p: 5.0
>  * /scaled_vel_joint_traj_controller/gains/wrist_2_joint/d: 0.1
>  * /scaled_vel_joint_traj_controller/gains/wrist_2_joint/i: 0.05
>  * /scaled_vel_joint_traj_controller/gains/wrist_2_joint/i_clamp: 1
>  * /scaled_vel_joint_traj_controller/gains/wrist_2_joint/p: 5.0
>  * /scaled_vel_joint_traj_controller/gains/wrist_3_joint/d: 0.1
>  * /scaled_vel_joint_traj_controller/gains/wrist_3_joint/i: 0.05
>  * /scaled_vel_joint_traj_controller/gains/wrist_3_joint/i_clamp: 1
>  * /scaled_vel_joint_traj_controller/gains/wrist_3_joint/p: 5.0
>  * /scaled_vel_joint_traj_controller/joints: ['shoulder_pan_jo...
>  * /scaled_vel_joint_traj_controller/state_publish_rate: 125
>  * /scaled_vel_joint_traj_controller/stop_trajectory_duration: 0.5
>  * /scaled_vel_joint_traj_controller/type: velocity_controll...
>  * /scaled_vel_joint_traj_controller/velocity_ff/elbow_joint: 1.0
>  * /scaled_vel_joint_traj_controller/velocity_ff/shoulder_lift_joint: 1.0
>  * /scaled_vel_joint_traj_controller/velocity_ff/shoulder_pan_joint: 1.0
>  * /scaled_vel_joint_traj_controller/velocity_ff/wrist_1_joint: 1.0
>  * /scaled_vel_joint_traj_controller/velocity_ff/wrist_2_joint: 1.0
>  * /scaled_vel_joint_traj_controller/velocity_ff/wrist_3_joint: 1.0
>  * /speed_scaling_state_controller/publish_rate: 125
>  * /speed_scaling_state_controller/type: scaled_controller...
>  * /twist_controller/frame_id: tool0_controller
>  * /twist_controller/joints: ['shoulder_pan_jo...
>  * /twist_controller/publish_rate: 125
>  * /twist_controller/type: ros_controllers_c...
>  * /ur_hardware_interface/headless_mode: False
>  * /ur_hardware_interface/input_recipe_file: /home/sgn/vs_ws/s...
>  * /ur_hardware_interface/joints: ['shoulder_pan_jo...
>  * /ur_hardware_interface/kinematics/forearm/pitch: -0.000594537154484
>  * /ur_hardware_interface/kinematics/forearm/roll: 0.00884206044624
>  * /ur_hardware_interface/kinematics/forearm/x: -0.243757115958
>  * /ur_hardware_interface/kinematics/forearm/y: 0
>  * /ur_hardware_interface/kinematics/forearm/yaw: 8.40093359824e-05
>  * /ur_hardware_interface/kinematics/forearm/z: 0
>  * /ur_hardware_interface/kinematics/hash: calib_17261210906...
>  * /ur_hardware_interface/kinematics/shoulder/pitch: 0
>  * /ur_hardware_interface/kinematics/shoulder/roll: 0
>  * /ur_hardware_interface/kinematics/shoulder/x: 0
>  * /ur_hardware_interface/kinematics/shoulder/y: 0
>  * /ur_hardware_interface/kinematics/shoulder/yaw: 3.42330098138e-06
>  * /ur_hardware_interface/kinematics/shoulder/z: 0.151972115745
>  * /ur_hardware_interface/kinematics/upper_arm/pitch: 0
>  * /ur_hardware_interface/kinematics/upper_arm/roll: 1.57148802257
>  * /ur_hardware_interface/kinematics/upper_arm/x: -7.3004204654e-05
>  * /ur_hardware_interface/kinematics/upper_arm/y: 0
>  * /ur_hardware_interface/kinematics/upper_arm/yaw: 3.08983387471e-05
>  * /ur_hardware_interface/kinematics/upper_arm/z: 0
>  * /ur_hardware_interface/kinematics/wrist_1/pitch: 3.14047042503
>  * /ur_hardware_interface/kinematics/wrist_1/roll: 3.13767367089
>  * /ur_hardware_interface/kinematics/wrist_1/x: -0.213299025792
>  * /ur_hardware_interface/kinematics/wrist_1/y: 0.000440661481425
>  * /ur_hardware_interface/kinematics/wrist_1/yaw: -3.14153768691
>  * /ur_hardware_interface/kinematics/wrist_1/z: 0.112442248294
>  * /ur_hardware_interface/kinematics/wrist_2/pitch: 0
>  * /ur_hardware_interface/kinematics/wrist_2/roll: 1.57114859111
>  * /ur_hardware_interface/kinematics/wrist_2/x: 3.09454100617e-05
>  * /ur_hardware_interface/kinematics/wrist_2/y: -0.0852101395564
>  * /ur_hardware_interface/kinematics/wrist_2/yaw: 1.15495100772e-06
>  * /ur_hardware_interface/kinematics/wrist_2/z: -3.00164923403e-05
>  * /ur_hardware_interface/kinematics/wrist_3/pitch: 3.14159265359
>  * /ur_hardware_interface/kinematics/wrist_3/roll: 1.56949305684
>  * /ur_hardware_interface/kinematics/wrist_3/x: 0.000101360722915
>  * /ur_hardware_interface/kinematics/wrist_3/y: 0.0823447434392
>  * /ur_hardware_interface/kinematics/wrist_3/yaw: 3.14156891529
>  * /ur_hardware_interface/kinematics/wrist_3/z: -0.000107317490541
>  * /ur_hardware_interface/output_recipe_file: /home/sgn/vs_ws/s...
>  * /ur_hardware_interface/reverse_ip: 
>  * /ur_hardware_interface/reverse_port: 50001
>  * /ur_hardware_interface/robot_ip: 192.168.56.1
>  * /ur_hardware_interface/script_command_port: 50004
>  * /ur_hardware_interface/script_file: /opt/ros/melodic/...
>  * /ur_hardware_interface/script_sender_port: 50002
>  * /ur_hardware_interface/servoj_gain: 2000
>  * /ur_hardware_interface/servoj_lookahead_time: 0.03
>  * /ur_hardware_interface/tf_prefix: 
>  * /ur_hardware_interface/tool_baud_rate: 115200
>  * /ur_hardware_interface/tool_parity: 0
>  * /ur_hardware_interface/tool_rx_idle_chars: 1.5
>  * /ur_hardware_interface/tool_stop_bits: 1
>  * /ur_hardware_interface/tool_tx_idle_chars: 3.5
>  * /ur_hardware_interface/tool_voltage: 0
>  * /ur_hardware_interface/trajectory_port: 50003
>  * /ur_hardware_interface/use_tool_communication: False
>  * /vel_joint_traj_controller/action_monitor_rate: 20
>  * /vel_joint_traj_controller/constraints/elbow_joint/goal: 0.1
>  * /vel_joint_traj_controller/constraints/elbow_joint/trajectory: 0.1
>  * /vel_joint_traj_controller/constraints/goal_time: 0.6
>  * /vel_joint_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
>  * /vel_joint_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
>  * /vel_joint_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
>  * /vel_joint_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
>  * /vel_joint_traj_controller/constraints/stopped_velocity_tolerance: 0.05
>  * /vel_joint_traj_controller/constraints/wrist_1_joint/goal: 0.1
>  * /vel_joint_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
>  * /vel_joint_traj_controller/constraints/wrist_2_joint/goal: 0.1
>  * /vel_joint_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
>  * /vel_joint_traj_controller/constraints/wrist_3_joint/goal: 0.1
>  * /vel_joint_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
>  * /vel_joint_traj_controller/gains/elbow_joint/d: 0.1
>  * /vel_joint_traj_controller/gains/elbow_joint/i: 0.05
>  * /vel_joint_traj_controller/gains/elbow_joint/i_clamp: 1
>  * /vel_joint_traj_controller/gains/elbow_joint/p: 5.0
>  * /vel_joint_traj_controller/gains/shoulder_lift_joint/d: 0.1
>  * /vel_joint_traj_controller/gains/shoulder_lift_joint/i: 0.05
>  * /vel_joint_traj_controller/gains/shoulder_lift_joint/i_clamp: 1
>  * /vel_joint_traj_controller/gains/shoulder_lift_joint/p: 5.0
>  * /vel_joint_traj_controller/gains/shoulder_pan_joint/d: 0.1
>  * /vel_joint_traj_controller/gains/shoulder_pan_joint/i: 0.05
>  * /vel_joint_traj_controller/gains/shoulder_pan_joint/i_clamp: 1
>  * /vel_joint_traj_controller/gains/shoulder_pan_joint/p: 5.0
>  * /vel_joint_traj_controller/gains/wrist_1_joint/d: 0.1
>  * /vel_joint_traj_controller/gains/wrist_1_joint/i: 0.05
>  * /vel_joint_traj_controller/gains/wrist_1_joint/i_clamp: 1
>  * /vel_joint_traj_controller/gains/wrist_1_joint/p: 5.0
>  * /vel_joint_traj_controller/gains/wrist_2_joint/d: 0.1
>  * /vel_joint_traj_controller/gains/wrist_2_joint/i: 0.05
>  * /vel_joint_traj_controller/gains/wrist_2_joint/i_clamp: 1
>  * /vel_joint_traj_controller/gains/wrist_2_joint/p: 5.0
>  * /vel_joint_traj_controller/gains/wrist_3_joint/d: 0.1
>  * /vel_joint_traj_controller/gains/wrist_3_joint/i: 0.05
>  * /vel_joint_traj_controller/gains/wrist_3_joint/i_clamp: 1
>  * /vel_joint_traj_controller/gains/wrist_3_joint/p: 5.0
>  * /vel_joint_traj_controller/joints: ['shoulder_pan_jo...
>  * /vel_joint_traj_controller/state_publish_rate: 125
>  * /vel_joint_traj_controller/stop_trajectory_duration: 0.5
>  * /vel_joint_traj_controller/type: velocity_controll...
>  * /vel_joint_traj_controller/velocity_ff/elbow_joint: 1.0
>  * /vel_joint_traj_controller/velocity_ff/shoulder_lift_joint: 1.0
>  * /vel_joint_traj_controller/velocity_ff/shoulder_pan_joint: 1.0
>  * /vel_joint_traj_controller/velocity_ff/wrist_1_joint: 1.0
>  * /vel_joint_traj_controller/velocity_ff/wrist_2_joint: 1.0
>  * /vel_joint_traj_controller/velocity_ff/wrist_3_joint: 1.0
> 
> NODES
>   /
>     controller_stopper (controller_stopper/node)
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     ros_control_controller_spawner (controller_manager/spawner)
>     ros_control_stopped_spawner (controller_manager/spawner)
>     ur_hardware_interface (ur_robot_driver/ur_robot_driver_node)
>   /ur_hardware_interface/
>     ur_robot_state_helper (ur_robot_driver/robot_state_helper)
> 
> auto-starting new master
> process[master]: started with pid [8002]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 7b359b70-807e-11ed-87f9-f02f74a14b89
> process[rosout-1]: started with pid [8013]
> started core service [/rosout]
> process[robot_state_publisher-2]: started with pid [8020]
> process[ur_hardware_interface-3]: started with pid [8021]
> process[ros_control_controller_spawner-4]: started with pid [8022]
> process[ros_control_stopped_spawner-5]: started with pid [8023]
> process[controller_stopper-6]: started with pid [8029]
> process[ur_hardware_interface/ur_robot_state_helper-7]: started with pid [8037]
> [ INFO] [1671551625.091830603]: Initializing dashboard client
> [ INFO] [1671551625.098971271]: Connected: Universal Robots Dashboard Server
> [ INFO] [1671551625.099653595]: Waiting for controller manager service to come up on /controller_manager/switch_controller
> [ INFO] [1671551625.102348526]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
> [ INFO] [1671551625.112439124]: Initializing urdriver
> [ WARN] [1671551625.113342112]: No realtime capabilities found. Consider using a realtime system for better performance
> [INFO] [1671551625.363149]: Controller Spawner: Waiting for service controller_manager/load_controller
> [INFO] [1671551625.365676]: Controller Spawner: Waiting for service controller_manager/load_controller
> [ INFO] [1671551625.502529435]: Negotiated RTDE protocol version to 2.
> [ INFO] [1671551625.502965786]: Setting up RTDE communication with frequency 125.000000
> [FATAL] [1671551631.516733597]: Variable 'tcp_offset' not recognized by the robot. Probably your output recipe contains errors
> [ERROR] [1671551631.516866722]: Could not correctly initialize robot. Exiting
>REQUIRED process [ur_hardware_interface-3] has died!
> process has died [pid 8021, exit code 1, cmd /home/sgn/vs_ws/devel/lib/ur_robot_driver/ur_robot_driver_node __name:=ur_hardware_interface __log:=/home/sgn/.ros/log/7b359b70-807e-11ed-87f9-f02f74a14b89/ur_hardware_interface-3.log].
> log file: /home/sgn/.ros/log/7b359b70-807e-11ed-87f9-f02f74a14b89/ur_hardware_interface-3*.log
> Initiating shutdown!

> [ur_hardware_interface/ur_robot_state_helper-7] killing on exit
> [ros_control_stopped_spawner-5] killing on exit
> [controller_stopper-6] killing on exit
> [ros_control_controller_spawner-4] killing on exit
> [ur_hardware_interface-3] killing on exit
> [robot_state_publisher-2] killing on exit
> [WARN] [1671551631.815157]: Controller Spawner couldn't find the expected controller_manager ROS interface.
> [WARN] [1671551631.841545]: Controller Spawner couldn't find the expected controller_manager ROS interface.
> [controller_stopper-6] escalating to SIGTERM
> [rosout-1] killing on exit
> [master] killing on exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done

The driver end up like this.
First I thought this error was caused by the calibration settings, but after I generated 'ur3_calibration.yaml' nothing changed. Does anyone know how to deal with this error? 

Inside ur3_calibration.yaml is like this

> kinematics:
>   shoulder:
>     x: 0
>     y: 0
>     z: 0.151972115745348
>     roll: -0
>     pitch: 0
>     yaw: 3.423300981382573e-06
>   upper_arm:
>     x: -7.300420465396063e-05
>     y: 0
>     z: 0
>     roll: 1.571488022568232
>     pitch: 0
>     yaw: 3.08983387471155e-05
>   forearm:
>     x: -0.2437571159582895
>     y: 0
>     z: 0
>     roll: 0.008842060446244662
>     pitch: -0.0005945371544843482
>     yaw: 8.400933598238956e-05
>   wrist_1:
>     x: -0.2132990257918033
>     y: 0.0004406614814252092
>     z: 0.1124422482938933
>     roll: 3.137673670892866
>     pitch: 3.140470425033668
>     yaw: -3.141537686907337
>   wrist_2:
>     x: 3.094541006166176e-05
>     y: -0.08521013955641654
>     z: -3.001649234033404e-05
>     roll: 1.57114859110587
>     pitch: 0
>     yaw: 1.15495100771622e-06
>   wrist_3:
>     x: 0.0001013607229153992
>     y: 0.08234474343916717
>     z: -0.0001073174905407372
>     roll: 1.569493056843488
>     pitch: 3.141592653589793
>     yaw: 3.141568915285252
>   hash: calib_17261210906883890926

## Use Case and Setup
PC network settings:
IPv4 address :192.168.56.11
netmask:255.255.255.0
gateway:192.168.56.1

UR3 network settings:
IP address:192.168.56.1
subnetmask:255.255.255.0
default gateway:192.168.56.11

Ecternal Control network settings:
Host IP:192.168.56.1
Custom Port:50002

## Project status at point of discovered
*When did you first observe the issue?*
 - yesterday
 - I worked hard to find similar error but couldn't find one.

## Steps to Reproduce
I also tried the command 
`
roslaunch ur_robot_driver ur3_bringup.launch robot_ip:=192.168.56.1 kinematics_config:=$(rospack find ur_robot_driver)/config/ur3_calibration.yaml [script_sender_port:=SCRIPT_SENDER_PORT]
`
but I got a same error.

I'm thinking running externalcontrol program properly in teaching pendant and setting custom port properly may solve this problem, but I don't know how.

## Expected Behavior
connection between ROS pc and UR3 will be establshed.

## Actual Behavior
ur3_bringup.launch is terminated.

**Comment by 7519060** [comment]
I'm so sorry for not previewing the issue before I post. I didn't know I could preview. It seems something went wrong when I paste error messages and codes.

**Comment by hantong96** [comment]
I had the same problem.
ur10 3.10.1
ubuntu18.04 melodic
externalcontrol-1.0.5.urcap

**Comment by fmauch** [comment]
Hi thank you for reporting this. This is definitively a regression introduced in #566.

**Comment by fmauch** [comment]
Recalling on this. As #566 states, the minimum required Polyscope version would be 3.12.0. @hantong96 you use 3.10.1. @7519060 you use 3.8.0.

We need to update our documentation.

**Comment by 7519060** [comment]
@fmauch 
Thank you for your reply.
I updated my polyscope version to 3.15.8 and it worked!
