### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by hxqhaoxinqing** [UniversalRobots/Universal_Robots_ROS_Driver#602]
# a make error

*Introduction to the issue*

# Impact
when i try to catkin make the package on ubuntu20.04,it find a error that make me cannot finish it.

# Issue details
```
/usr/bin/ld: /opt/ros/noetic/lib/libroscpp.so: undefined reference to `boost::detail::set_tss_data(void const*, void (*)(void (*)(void*), void*), void (*)(void*), void*, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [Universal_Robots_ROS_Driver/controller_stopper/CMakeFiles/controller_stopper_node.dir/build.make:116: /home/ros/ur_ws/devel/lib/controller_stopper/node] Error 1
make[1]: *** [CMakeFiles/Makefile2:2381: Universal_Robots_ROS_Driver/controller_stopper/CMakeFiles/controller_stopper_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

## Steps to Reproduce
it is mainly about the controller_stopper

## Expected Behavior
catkin make successfully

## Actual Behavior
meet a error

## Workaround Suggestion
*If a workaround has been found, you are welcome to share.*

**Comment by fmauch** [comment]
This looks like a local build problem and should be resolvable from your side. Could you please make sure that

* Your system is up-to-date (`sudo apt update && sudo apt dist-upgrade`)
* Your workspace is rebuilt from scratch (go to your `catkin_ws` folder and delete the `build` and `devel` folder (or `build_isolated` / `devel_isolated` respectively). Then, build your workspace.
