### ISSUE TITLE
Compile error: An expression was found which produces a result that is not used un the program

### ISSUE THREAD

**Issue by Rodpc07** [UniversalRobots/Universal_Robots_ROS_Driver#622]
# Summary

**(Using URSIM on Docker for controlling a simulated UR5 with ROS)** 

When trying to execute the external control program the following error occurs:

![image](https://user-images.githubusercontent.com/49754346/225732739-7bdbf1ba-4a0c-4092-8c4d-e64a84d32a93.png)

Weirdly enough, when the PC is connect to mobile data through hotspot the error doesn't occurs, prompting a window saying the program is starting with a loading bar.

I'm new to this program and Docker, so any help is appreciated.

# Versions
 - ROS Driver version: 2.0.0
 - Affected Robot Software Version(s): Universal Robots simulator for e-Series:5.13.0
 - Affected Robot Hardware Version(s):
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s): 1.0.5

**Comment by RobertWilbrandt** [comment]
That is indeed very weird. Can you describe exactly how you arrived at this error? Did you follow the description [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/install_urcap_e_series.md)? Could you also check if [headless mode](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/README.md#headless-mode) also leads to this problem?
