### ISSUE TITLE
Feature Requests for E-Series Force Torque Sensor ROS Controller

### ISSUE THREAD

**Issue by ian-chuang** [UniversalRobots/Universal_Robots_ROS_Driver#626]
I've noticed that the ROS driver for the force torque sensor that comes with the E-Series is a bit limited in its functionality. Currently, the only control you have over the sensor is that you can call a service to zero out its values. 

It would be nice then if we had more control over the FT sensor, similar to the ROS package for the [ATI sensor](http://wiki.ros.org/ati_force_torque). For example, having some options for unzeroing the sensor and reading raw data, doing gravity compensation, and applying a low pass filter would be helpful.

For my application where I want to do cartesian force control, having a gravity compensation feature that given the center of mass of a gripper/payload, offsets any gravity forces caused by the end effector rotating would be appreciated. Perhaps you can specify gravity, center of mass of the payload, and mass of the payload within the [force torque sensor controller config](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/395c0541b20d0da2cd480e2ad85b2100410fb043/ur_robot_driver/config/ur5e_controllers.yaml#L21).

Would this feature be better off implemented within the [ROS controllers package](https://github.com/ros-controls/ros_controllers/tree/noetic-devel/force_torque_sensor_controller) instead?

This isn't a high priority request, but is still a feature that I think others would appreciate as well. [Stefan Scherzinger suggested I open an issue here in this thread.](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/120#issuecomment-1483767128)

**Comment by miguelprada** [comment]
It's my understanding that the FT sensor measurements provided by the driver through its force-torque sensor interface already contains data where the tool payload has been compensated by the robot controller itself (the values are read from the [`actual_TCP_force` RTDE entry](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/395c0541b20d0da2cd480e2ad85b2100410fb043/ur_robot_driver/src/hardware_interface.cpp#L506) which, according to the [reference](https://www.universal-robots.com/articles/ur/interface-communication/real-time-data-exchange-rtde-guide/) already _"compensates for forces and torques generated by the payload"_). Have you tried to play around with the `set_payload` service and check whether the measurements change accordingly?

As for the low pass (or other) filters, I'd argue there may be very different requirements for this in different scenarios. My opinion is that this would be better handled at the individual controller level.
