### ISSUE TITLE
complete support for ur16e?

### ISSUE THREAD

**Issue by loubron23** [UniversalRobots/Universal_Robots_ROS_Driver#645]
I need to use the UR16e with support for  MoveIt!.

So is there any version I can use?

**Comment by fmauch** [comment]
Hi, thank you for your interest in using our driver. Unfortunately, the moveit config is not part of this repository.

However, did you try [`ur16e_moveit_config`](https://index.ros.org/p/ur16e_moveit_config/github-ros-industrial-universal_robot/#noetic)?

If there is a bug with that, please open an issue in https://github.com/ros-industrial/universal_robot/tree/melodic-devel/ur16e_moveit_config. However, to my knowledge the package does work, so please open an issue if there is something severely wrong with the package. Tank you.
