### ISSUE TITLE
How to control UR5e with different controllers under different namespaces?

### ISSUE THREAD

**Issue by ZZWang21** [UniversalRobots/Universal_Robots_ROS_Driver#651]
I am trying to control a UR5e robot in Gazebo+Moveit+RViz. 
# Versions
 - ROS Noetic.
 - UBUNTU 20.04

I used a cartesian_compliance controller under default group namespace (control the compliance and micro movement of the robot) and another position controller under "group ns"- "joint_controller" (to control the position movement of the robot). But the "joint_controller" never took actions. 

The position controller, in this case "joint_controller/arm_controller" can receive actual positions, target positions and errors. but after I set targets, it never execute it. 

        <group ns="my_joint_to_cartesian_controller" >
                  <node name="controller_spawner_mjtcc" pkg="controller_manager" type="spawner" args="arm_controller" />
         </group>

Could any expert help me out here? Thank you very much.

**Comment by RobertWilbrandt** [comment]
I cannot quite follow what exactly you are doing. Can you share the controller config file you use for these controllers? And what exactly do you do to start/stop your controllers and which commands are you sending? Did you make sure to stop the compliance controller before starting your joint controller?
