### ISSUE TITLE
UR5 driver on ROS noetic

### ISSUE THREAD

**Issue by miladasgari178** [UniversalRobots/Universal_Robots_ROS_Driver#660]
# Summary

I am trying to create a package of UR5 for ROS noetic according to this tutorial "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver", but it seems it just works for ROS melodic, does anyone know what can I do to install ROS packages of UR5 on ROS noetic?

**Comment by fmauch** [comment]
As written in #661 and #254 it is available on noetic. Updating the documentation regarding this currently happens in #655
