### ISSUE TITLE
I can't build hardware_interface.cpp in Universal_Robots_ROS_Driver

### ISSUE THREAD

**Issue by liujun0808** [UniversalRobots/Universal_Robots_ROS_Driver#674]
### Affected ROS Driver version(s)

Universal_ROS_driver

### Used ROS distribution.

Melodic

### Which combination of platform is the ROS driver running on.

Linux in a virtual machine

### How is the UR ROS Driver installed.

Build the driver from source and using the UR Client Library from binary

### Which robot platform is the driver connected to.

UR CB3 robot

### Robot SW / URSim version(s)

URSoftware 3.9.0.64176(Mar 01 2019)

### How is the ROS driver used.

Through the robot teach pendant using External Control URCap

### Issue details

# Summary
Failed to build hardware_interface.cpp. .

### Accept Public visibility

- [x] I agree to make this context public

**Comment by RobertWilbrandt** [comment]
Melodic is [End of Life](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023) and as such it is expected that more things like this will break with time. You should consider switching to noetic as more problems like this will appear in the future. With that said:

The [Universal Robots Client Library](https://github.com/UniversalRobots/Universal_Robots_Client_Library) introduced spline interpolation with release 1.3.2 (see [Changelog](https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/master/CHANGELOG.rst)). The last released library version for melodic was 1.3.1, so you can try two options:
1. Try building the current `ur_client_library` from source.
2. Switch to the corresponding older version of this driver (`git checkout v2.1.2` should do it)

Please let us know if this fixes your problem.

**Comment by liujun0808** [comment]
> Melodic is [End of Life](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023) and as such it is expected that more things like this will break with time. You should consider switching to noetic as more problems like this will appear in the future. With that said:
> 
> The [Universal Robots Client Library](https://github.com/UniversalRobots/Universal_Robots_Client_Library) introduced spline interpolation with release 1.3.2 (see [Changelog](https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/master/CHANGELOG.rst)). The last released library version for melodic was 1.3.1, so you can try two options:
> 
> 1. Try building the current `ur_client_library` from source.
> 2. Switch to the corresponding older version of this driver (`git checkout v2.1.2` should do it)
> 
> Please let us know if this fixes your problem.
Thanks！I understand the problem.I tried using the first option，but i don't konw how to build it from source.
 I try to add writeTrajectorySplinePoint to ur_driver.h in ur_client_library,but i can't find ur_driver.cpp in ur_client_library.Is this normal?
 When I added the declaration before compiling the Work_Space, the error result was an undefined reference.
I am a beginner in this field，Could you please tell me more details about option one?
Looking forward to your reply!

**Comment by liujun0808** [comment]
Thanks！I understand the problem.I tried using the first option，but i don't konw how to build it from source.
I try to add writeTrajectorySplinePoint to ur_driver.h in ur_client_library,but i can't find ur_driver.cpp in ur_client_library.Is this normal?
When I added the declaration before compiling the Work_Space, the error result was an undefined reference.
I am a beginner in this field，Could you please tell me more details about option one?
Looking forward to your reply!


| |
liujun
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/4/2023 22:53 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [UniversalRobots/Universal_Robots_ROS_Driver] I can't build hardware_interface.cpp in Universal_Robots_ROS_Driver (Issue #674) |

Melodic is End of Life and as such it is expected that more things like this will break with time. You should consider switching to noetic as more problems like this will appear in the future. With that said:

The Universal Robots Client Library introduced spline interpolation with release 1.3.2 (see Changelog). The last released library version for melodic was 1.3.1, so you can try two options:

Try building the current ur_client_library from source.
Switch to the corresponding older version of this driver (git checkout v2.1.2 should do it)

Please let us know if this fixes your problem.

**Comment by SK8Era** [comment]
I am also having problems with hardware_interface.cpp and ur_client_library, and my environment is ROS-noetic and Ubuntu 20.04
![2023-12-20 21-55-45 的屏幕截图](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/92249300/7d5e8c32-ea95-42d5-99cf-2609e1f1f262)

**Comment by liujun0808** [comment]
很久了，我有点忘记了，melodic版本的driver没有那个spline函数，我的做法是把相关spline函数都给注释掉了，但不知道在以后得使用中会不会出现什么问题。
| |
liujun
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/20/2023 21:56 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [UniversalRobots/Universal_Robots_ROS_Driver] I can't build hardware_interface.cpp in Universal_Robots_ROS_Driver (Issue #674) |

I am also having problems with hardware_interface.cpp and ur_client_library, and my environment is ROS-noetic and Ubuntu 20.04
2023-12-20.21-55-45.png (view on web)

**Comment by fmauch** [comment]
Unless there is a specific reason why you want to build things from source, I suggest to use the apt packages as described in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver?tab=readme-ov-file#install-from-binary-packages.

Otherwise, please remove the binary package for the client library (`sudo apt remove ros-noetic-ur-client-library`), make sure to have the latest version checked out and build your workspace from a clean state.

I'll go ahead and close this issue, since the proposed solution should work and there haven't been any updates, lately. Feel free to comment / reopen if the issue persists.
