### ISSUE TITLE
Cannot connect to robot

### ISSUE THREAD

**Issue by trngqung14** [UniversalRobots/Universal_Robots_ROS_Driver#692]
I run command roslaunch ur_robot_driver ur5_bring_up.launch robot_ip:=192.168.0.101

Failed to connect to robot on IP 192.168.0.101. Please check that the robot is booted and reachable on 192.168.0.101.

I have done ping, source, catkin_make and check IP address and network in Polyscope and it's still error

**Comment by RobertWilbrandt** [comment]
Please add some more information to the issue:
- What is your host IP address? Are you running the driver directly on a Ubuntu 20.04? Does `ping 192.168.0.101` work?
- Please provide the driver log output

**Comment by trngqung14** [comment]
my host IP in Polyscope is 192.168.0.101, Polyscope version is 3.15.5,
![z5309866449309_73f124a7382cb22e9a3233377e7bd23f](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/117334186/f748883e-f54d-4b62-a834-7bddd96fec43)
![z5309866460499_47bc66b0783b4999eca7b19a5a47c8a7](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/117334186/d79ef37d-a1f5-4cbd-bed2-5d59ca973a01)
![z5309866488604_1058b39a92392f341e2e228ad7cfc05b](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/117334186/51bfdbf4-4d5d-4a58-9c56-7abd0c1a3272)
 i am using ubuntu 20.04 on VM and ping worked
i have set ethernet in window 192.168.0.101, changed network of VM to Bridge Adapter and set IP in linux network 192.168.0.101
driver log output is below
[ERROR] [1712046723.448455422]: Failed to connect to robot on IP 192.168.0.101. Please check that the robot is booted and reachable on 192.168.0.101. Retrying in 10 seconds

**Comment by Yeesha-R** [comment]
It seems that your robot's IP address is the same as your computer's IP address. This could be the potential cause of the error.

**Comment by trngqung14** [comment]
@Yeesha-R when i change IP of computer and network in linux to 192.168.0.10 like the hostname in Polyscope, it still does not work. 
my robot is ur5 cb series but output remains about cb3 and e series.
![z5310055287624_a8e18c51e1a339aa3f70e91d5421b6ff](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/117334186/3b03d3ca-cb42-4a63-a410-437ef881ce21)

**Comment by Yeesha-R** [comment]
@trngqung14, I do not have a solution for this error. However, you can take a look at issue [#510](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/510) to see if it provides any assistance.

**Comment by trngqung14** [comment]
Im still cannot fix this problem

**Comment by Yeesha-R** [comment]
@trngqung14 according to the error prompt, the issue could be due to the software version of your polyscope. Could you check if the software version of your polyscope is at least 3.12.0?

**Comment by RobertWilbrandt** [comment]
I still don't get what your network setup looks like right now. What exactly are the ip addresses of:
- The robot (probably `192.168.0.101`)?
- Your host?
- The ubuntu VM?
- Is the host ip for the external control program correctly set to the ip of your ubuntu vm?

All of these need to be different, your network interface in the vm needs to be set to Bridge Adapter and you have to be able to ping the robot from your ubuntu VM.

You say that you currently have polyscope version 3.15.5 installed, which should be fine (see [requirements](https://github.com/UniversalRobots/Universal_Robots_Client_Library?tab=readme-ov-file#requirements)). Do you have a different program or PLC trying to control the UR IOs? This is currently not supported.
