### ISSUE TITLE
received program failed

### ISSUE THREAD

**Issue by shen-shui** [UniversalRobots/Universal_Robots_ROS_Driver#697]
version：ros noetic
               ur3
               ursoftware 3.15.8

issue：When I use 
`roslaunch ur_robot_driver ur3_bringup.launch robot_ip:=192.168.100.100` 
I can get the correct feedback
![image](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/84558898/a23620b6-5187-42af-b6cc-3c9ed9e4d4a6)
But when I start the `external controller` program, a receive program failed error occurs. My virtual machine can ping the IP of the UR robot arm normally.
![IMG_20240416_213937](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/assets/84558898/a16c6cfc-310d-44b4-b05c-040bf3b3813f)

**Comment by fmauch** [comment]
If I understand correctly, you are trying to run the driver inside a virtual machine? In that case, I will refer you to https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/623#issuecomment-1603683956 and close this issue as a duplicate.

If you think that the linked answer does not apply to you, feel free to reopen this issue.
