### ISSUE TITLE
Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]

### ISSUE THREAD

**Issue by Guanxiaolong0408** [UniversalRobots/Universal_Robots_ROS_Driver#70]
I using easy_handeye to calibrate the UR5 and depth camera, all the driver has been installed ,  while I using the rqt_easy_handeye to execute the plan, the robot on the rviz could move , **but the real robot cannot move** , and there is errors as 

[ INFO] [1576755856.511674999]: Execution request received
[ INFO] [1576755856.511729324]: Returned 0 controllers in list
[ERROR] [1576755856.511757687]: Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]
[ERROR] [1576755856.511782182]: Known controllers and their joints:

Is there any one meet this problem?

**Comment by fmauch** [comment]
As far as I see, this uses MoveIt!, so it might be related to #55. If so, [this comment](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/55#issuecomment-562215033) might help you. Feel free to participate in the discussion inside #55.

**Comment by fmauch** [comment]
Any news on this? Otherwise I will consider closing this in a future sweep through the issues.

**Comment by mn-banjar** [comment]
> I using easy_handeye to calibrate the UR5 and depth camera, all the driver has been installed , while I using the rqt_easy_handeye to execute the plan, the robot on the rviz could move , **but the real robot cannot move** , and there is errors as
> 
> [ INFO] [1576755856.511674999]: Execution request received
> [ INFO] [1576755856.511729324]: Returned 0 controllers in list
> [ERROR] [1576755856.511757687]: Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]
> [ERROR] [1576755856.511782182]: Known controllers and their joints:
> 
> Is there any one meet this problem?

I faced the same issue when I was trying to use an example package that uses Moveit.

In my case, I forget to install Moveit package on the ROS. so I solved the issue by running:

`sudo apt-get install ros-kinetic-moveit`

**Comment by EAzar02** [comment]
hi, is there a solution for this in ros2? im currently using ros2 humble, moveit2 as well as rviz2 and it keeps showing the same error for some reason. i read through #55 but couldnt conclude a solution. and the moveit_config files were setup using the assistant launcher.
