### ISSUE TITLE
Tool communication parameter `tool_rx_idle_chars`/`tool_tx_idle_chars` is not set correctly

### ISSUE THREAD

**Issue by kamikat** [UniversalRobots/Universal_Robots_ROS_Driver#726]
### Affected ROS Driver version(s)

master

### Used ROS distribution.

Noetic

### Which combination of platform is the ROS driver running on.

Linux

### How is the UR ROS Driver installed.

Build the driver from source and using the UR Client Library from binary

### Which robot platform is the driver connected to.

UR E-series robot

### Robot SW / URSim version(s)

5.12.5

### How is the ROS driver used.

Others

### Issue details

# Summary
Launch parameter `tool_rx_idle_chars`/`tool_tx_idle_chars` is not correctly set for tool communication.

## Steps to Reproduce
1. Launch driver with `use_tool_communication:=true`
2. Open I/O panel on PolyScope

## Expected Behavior
I/O panel on PolyScope shows "RX Idle Chars: 1.5 / TX Idle Chars: 3.5"

## Actual Behavior
I/O panel on PolyScope shows "RX Idle Chars: 2 / TX Idle Chars: 4"

# Workaround Suggestion

Patch `rx_idle_chars` and `tx_idle_chars` to `float` type.

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/5407dfe7aa623f75eec93fae8cd1ce15e8d6780e/ur_robot_driver/src/hardware_interface.cpp#L250-L261

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/5407dfe7aa623f75eec93fae8cd1ce15e8d6780e/ur_robot_driver/src/hardware_interface.cpp#L264-L275

### Accept Public visibility

- [X] I agree to make this context public

**Comment by fmauch** [comment]
Oh my, this is absolutely correct! I'll provide a fix ASAP.
