### ISSUE TITLE
Install from binary package not working

### ISSUE THREAD

**Issue by sharpworks-dev** [UniversalRobots/Universal_Robots_ROS_Driver#727]
### Affected ROS Driver version(s)

ROS Noetic

### Used ROS distribution.

Noetic

### Which combination of platform is the ROS driver running on.

Linux in a virtual machine, Windows

### How is the UR ROS Driver installed.

From binary packets

### Which robot platform is the driver connected to.

UR E-series robot, Real robot

### Robot SW / URSim version(s)

unsure or n/a

### How is the ROS driver used.

Through the robot teach pendant using External Control URCap

### Issue details

# Summary
First time user, only very basic familiarity with ROS, trying to install the drivers to control a real UR3e robot from ROS Noetic in a Linux VM on Windows. I installed from binary packages as recommended in the install guide and it doesn't seem to recognize the packages. If I've missed something obvious I apologize, I just followed what the repo said to do and it isn't working.

## Issue details
After running `sudo apt install ros-noetic-ur-robot-driver` 
I source ROS again and run 
```
roslaunch ur_calibration calibration_correction.launch \
  robot_ip:=<robot_ip> target_filename:="${HOME}/my_robot_calibration.yaml"
``` 
and I get the error `RLException: [calibration_correction.launch] is neither a launch file in package [ur_calibration] nor is [ur_calibration] a launch file name`

## Steps to Reproduce
Follow the instructions in [install from binary packages](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver?tab=readme-ov-file#install-from-binary-packages) and [setting up a ur robot for ur_robot_driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver?tab=readme-ov-file#setting-up-a-ur-robot-for-ur_robot_driver)

## Expected Behavior
I expected the calibration nodes to run and extract the calibration info from my robot

## Actual Behavior
ROS didn't recognize the packages that should have been installed from the binaries

# Workaround Suggestion
n/a

### Accept Public visibility

- [X] I agree to make this context public

**Comment by fmauch** [comment]
Thank you for reporting. You are absolutely correct, there is no direct dependency from the driver package to the calibration package, so it will not be installed automatically. We should add that to the documentation.

To workaround the package for now, install the `ur_calibration` package manually:

```
sudo apt install ros-noetic-ur-calibration
```
