### ISSUE TITLE
'catkin_make' is failed when I tried to make a new package for receiving TCP F/T sensor value.

### ISSUE THREAD

**Issue by dkfwlak** [UniversalRobots/Universal_Robots_ROS_Driver#80]
# Summary

Trying to make a new package for receiving TCP F/T sensor value, but 'catkin_make' is failed.

# Versions
 - ROS Driver version: Melodic with Ubuntu 18.04 LTS
 - Affected Robot Software Version(s):  Over 5.1 with UR3e + OnRobot RG2
 - Affected Robot Hardware Version(s):
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s): 1.0.1

# Issue details

Hello.

First, I want you to know that I'm new with ROS but I have to make an UR3e moving while receiving TCP force/torque value with ROS.

I made the new package named 'ft_sensor' and a new message file 'ft_sensor.msg' by refer to 'hardware_interface.h' in 'Universal_Robots_ROS_Driver/ur_robot_driver/include/ur_robot_driver/ros/', whose content is:
tf2::Vector3 force
tf2::Vector3 torque.

But when I run 'catkin_make', I got following log:
 -- +++ processing catkin package: 'ft_sensor'
-- ==> add_subdirectory(ft_sensor)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
/opt/ros/melodic/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <class 'genmsg.base.InvalidMsgSpec'>: /home/mecha/catkin_ws/src/ft_sensor/msg/ft_sensor.msg: tf2::Vector3 is not a legal message field type
Traceback (most recent call last):
  File "/usr/bin/empy", line 3302, in <module>
    if __name__ == '__main__': main()
  File "/usr/bin/empy", line 3300, in main
    invoke(sys.argv[1:])
  File "/usr/bin/empy", line 3283, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/bin/empy", line 2295, in wrap
    self.fail(e)
  File "/usr/bin/empy", line 2284, in wrap
    callable(*args)
  File "/usr/bin/empy", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/bin/empy", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/bin/empy", line 2421, in parse
    token.run(self, locals)
  File "/usr/bin/empy", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/bin/empy", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "/usr/bin/empy", line 42, in _exec
    exec("""exec code in globals""")
  File "<string>", line 1, in <module>
  File "<string>", line 38, in <module>
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/deps.py", line 45, in find_msg_dependencies_with_type
    spec = genmsg.msg_loader.load_msg_from_file(msg_context, msg_file, full_type_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 289, in load_msg_from_file
    raise InvalidMsgSpec('%s: %s'%(file_path, e))
genmsg.base.InvalidMsgSpec: /home/mecha/catkin_ws/src/ft_sensor/msg/ft_sensor.msg: tf2::Vector3 is not a legal message field type
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/home/mecha/catkin_ws/build/catkin_generated/env_cached.sh
  "/usr/bin/python2" "/usr/bin/empy" "--raw-errors" "-F"
  "/home/mecha/catkin_ws/build/ft_sensor/cmake/ft_sensor-genmsg-context.py"
  "-o" "/home/mecha/catkin_ws/build/ft_sensor/cmake/ft_sensor-genmsg.cmake"
  "/opt/ros/melodic/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  ft_sensor/CMakeLists.txt:71 (generate_messages)

-- Configuring incomplete, errors occurred!

It seems that I used wrong variable type (tf2::Vector3), so I searched about Vector3 type. 

When I found http://docs.ros.org/melodic/api/geometry_msgs/html/msg/Vector3.html, it is described that it only represents a direction, but I need actual value of force/torque.

How should I make a message file for actual TCP force/torque value?

If you let me know any way to receive TCP force/torque value, I would really appreciate it.

I'm hoping there's a solution or more.

Thank you very much.

**Comment by fmauch** [comment]
Hi, first of all: Welcome to the ROS community!

From a driver's perspective, I'd suggest that you simply start the driver as explained in the setup guide. Then, there will be the ROS topic `/wrench` which will publish the robot's FTS mesurements. It uses a `geometry_msgs/WrenchStamped` message as `rostopic info /wrench` will also tell you.

From your catkin problem's perspective: As the output states, you are using an illegal type definition `tf2::Vector3`. The correct one would have been (as you already found) `geometry_msgs/Vector3`, as you can see in the [geometry_msgs/Wrench](http://docs.ros.org/melodic/api/geometry_msgs/html/msg/Wrench.html). The `geometry_msgs/WrenchStamped` uses that together with a `Header` that adds information about the time and frame where the data is recorded. Please see the [ROS tutorials on msgs](http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv) for further information on creating own messages.

At last, please let me state, that for this question [ROS Answers](https://answers.ros.org/questions/) would have been the better place, as it is not describing an issue with this package, but rather is a question on implementing something yourself. If you have any followup questions, please post a new issue there (or search for a similar topic first). I'll go ahead and close this issue.
