### ISSUE TITLE
When will velocity control be implemented?

### ISSUE THREAD

**Issue by akihikoy** [UniversalRobots/Universal_Robots_ROS_Driver#95]
Hi,

Could you tell me when you are going to implement a velocity control mode?

According to [Feature comparison and roadmap](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/261fac97ade85b0030d5fcfcc8eb9cc1f01654d8/ur_robot_driver/doc/features.md), it seems that implementing a velocity control mode is planned.  I would like to know when it will be released.

Many thanks!

**Comment by gavanderhoorn** [comment]
Have you seen #1 ?

**Comment by fmauch** [comment]
Have a look at #1. From my side this is currently under testing and reviewing before it can be merged. If you like, go ahead and test it and give feedback.

**Comment by akihikoy** [comment]
Great! I will test  #1.

**Comment by fmauch** [comment]
#1 got merged. Closing this.
